# backend\deploy-backend.ps1
param(
  # Example explicit image: asia-northeast1-docker.pkg.dev/<PROJECT>/<REPO>/<SERVICE>:<TAG>
  [string]$Image,

  # Region / Cloud Run service name
  [string]$Region      = "asia-northeast1",
  [string]$ServiceName = "narratives-backend",

  # Artifact Registry repository name (Docker)
  [string]$RepoName    = "narratives-backend",

  # If -Image is auto-generated and Docker is available, use local docker build/push.
  # If Docker is unavailable, fallback to Cloud Build automatically.
  [bool]$PreferDockerWhenAvailable = $true
)

$ErrorActionPreference = "Stop"

function Write-Step($msg) { Write-Host "== $msg ==" -ForegroundColor Cyan }
function Write-Ok($msg)   { Write-Host "OK: $msg" -ForegroundColor Green }
function Write-Warn($msg) { Write-Host "!! $msg" -ForegroundColor Yellow }

# ------------------------------------------------------------
# 0) gcloud のプロジェクト確認
# ------------------------------------------------------------
$ProjectId = (gcloud config get-value project 2>$null).Trim()
if (-not $ProjectId) {
  throw "gcloud config project is not set. Example: gcloud config set project <YOUR_PROJECT_ID>"
}
Write-Step "Using project: $ProjectId"

# Cloud Run service account
$RunServiceAccount = "narratives-backend-sa@$ProjectId.iam.gserviceaccount.com"

# スクリプト / ソースディレクトリ
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$SourceDir = $ScriptDir

# ------------------------------------------------------------
# 1) Go build チェック
# ------------------------------------------------------------
$MainGo = Join-Path $SourceDir "cmd\api\main.go"
if (-not (Test-Path $MainGo)) {
  throw "Go main file not found: $MainGo"
}

Write-Step "go build check (cmd/api)"
Push-Location $SourceDir
try {
  go version | Out-Null
  go build ./cmd/api
} finally {
  Pop-Location
}
Write-Ok "go build succeeded"

# ------------------------------------------------------------
# 2) Artifact Registry リポジトリ確認
# ------------------------------------------------------------
Write-Step "Ensuring Artifact Registry repository: ${RepoName}"
$repoExists = $true
try {
  gcloud artifacts repositories describe $RepoName --location=$Region --project=$ProjectId | Out-Null
} catch {
  $repoExists = $false
}

if (-not $repoExists) {
  Write-Warn "Repository '${RepoName}' not found. Creating it..."
  gcloud artifacts repositories create $RepoName `
    --repository-format=docker `
    --location=$Region `
    --description="Backend images for ${ServiceName}" `
    --project=$ProjectId | Out-Null
  Write-Ok "Repository created: ${RepoName}"
} else {
  Write-Ok "Repository exists: ${RepoName}"
}

# ------------------------------------------------------------
# 3) イメージ名決定
# ------------------------------------------------------------
$AutoGenerated = $false
if ([string]::IsNullOrWhiteSpace($Image)) {
  $RegistryHost = "${Region}-docker.pkg.dev"
  $Tag = Get-Date -Format "yyyyMMdd-HHmmss"
  $Image = "${RegistryHost}/${ProjectId}/${RepoName}/${ServiceName}:${Tag}"
  $AutoGenerated = $true
  Write-Step "No image specified. Generated image: $Image"
} else {
  Write-Step "Using specified image: $Image"
}

# ------------------------------------------------------------
# 4) ビルド & push (Docker 優先)
# ------------------------------------------------------------
function Test-DockerAvailable {
  try {
    docker info | Out-Null
    return $true
  } catch {
    return $false
  }
}

if ($AutoGenerated) {
  $DockerAvailable = $false
  if ($PreferDockerWhenAvailable) {
    $DockerAvailable = Test-DockerAvailable
  }

  if ($DockerAvailable) {
    Write-Step "Docker detected. Using local docker build & push"

    $RegistryHost = "${Region}-docker.pkg.dev"
    Write-Step "Configuring Docker auth for ${RegistryHost}"
    gcloud auth configure-docker "$RegistryHost" -q | Out-Null
    Write-Ok "Docker auth configured"

    Push-Location $SourceDir
    try {
      docker build -t "$Image" .
      if ($LASTEXITCODE -ne 0) { throw "docker build failed with exit code $LASTEXITCODE" }
      docker push "$Image"
      if ($LASTEXITCODE -ne 0) { throw "docker push failed with exit code $LASTEXITCODE" }
    } finally {
      Pop-Location
    }
    Write-Ok "Image build & push completed (Docker)"
  } else {
    Write-Step "Docker not available. Using Cloud Build"
    gcloud builds submit --tag "$Image" --project "$ProjectId"
    if ($LASTEXITCODE -ne 0) {
      throw "Cloud Build failed. exit code: $LASTEXITCODE"
    }
    Write-Ok "Image build & push completed (Cloud Build)"
  }
} else {
  Write-Warn "Auto-image disabled (explicit -Image). Skipping build/push."
}

# ------------------------------------------------------------
# 5) Cloud Run に渡す環境変数を組み立てる
#    - 基本は GOOGLE_CLOUD_PROJECT
#    - backend/.env から SendGrid, Console, Solana, Arweave(Irys) 関連を追加
# ------------------------------------------------------------
Write-Step "Collecting env vars for Cloud Run"

# まず必ずセットするもの
$envPairs = @("GOOGLE_CLOUD_PROJECT=$ProjectId")

# backend/.env を読む想定
$EnvFile = Join-Path $SourceDir ".env"
if (Test-Path $EnvFile) {
  Write-Ok "Found .env: $EnvFile"

  foreach ($line in Get-Content $EnvFile) {
    $trim = $line.Trim()
    if (-not $trim) { continue }            # 空行
    if ($trim.StartsWith("#")) { continue } # コメント

    $idx = $trim.IndexOf("=")
    if ($idx -lt 1) { continue }

    $key   = $trim.Substring(0, $idx).Trim()
    $value = $trim.Substring($idx + 1).Trim()

    # Cloud Run に渡したいキーだけをピックアップ
    if ($key -in @(
      "SENDGRID_API_KEY",
      "SENDGRID_FROM",
      "CONSOLE_BASE_URL",
      "SOLANA_RPC_URL",
      "SOLANA_MINT_KEY_SECRET",
      "ARWEAVE_BASE_URL"
    )) {
      $envPairs += "$key=$value"
    }
  }
} else {
  Write-Warn ".env file not found at $EnvFile. Only GOOGLE_CLOUD_PROJECT will be set."
}

$envArg = [string]::Join(",", $envPairs)
Write-Step "Env vars to set: $envArg"

# ------------------------------------------------------------
# 6) Cloud Run へデプロイ
# ------------------------------------------------------------
Write-Step "Deploying to Cloud Run"

$deployArgs = @(
  "run","deploy", $ServiceName,
  "--image",          $Image,
  "--region",         $Region,
  "--platform",       "managed",
  "--allow-unauthenticated",
  "--service-account", $RunServiceAccount,
  "--set-env-vars",    $envArg,
  "--min-instances",  "0",
  "--max-instances",  "5",
  "--memory",         "512Mi",
  "--cpu",            "1",
  "--concurrency",    "80",
  "--timeout",        "60s",
  "--project",        $ProjectId
)

& gcloud @deployArgs
if ($LASTEXITCODE -ne 0) {
  throw "gcloud run deploy failed. exit code: $LASTEXITCODE"
}

Write-Ok "Cloud Run deployment finished: service '${ServiceName}'"
if ($AutoGenerated) {
  Write-Ok "Deployed with image: ${Image}"
}
