param(
  [string]$Image,

  [string]$Region      = "asia-northeast1",
  [string]$ServiceName = "narratives-mall",

  [string]$RepoName    = "narratives-backend",

  [bool]$PreferPodmanWhenAvailable = $true
)

$ErrorActionPreference = "Stop"

function Write-Step($msg) { Write-Host "== $msg ==" -ForegroundColor Cyan }
function Write-Ok($msg)   { Write-Host "OK: $msg" -ForegroundColor Green }
function Write-Warn($msg) { Write-Host "!! $msg ==" -ForegroundColor Yellow }

function Normalize-EnvValue([string]$v) {
  if ($null -eq $v) { return "" }
  $s = $v.Trim()
  if (($s.StartsWith('"') -and $s.EndsWith('"')) -or ($s.StartsWith("'") -and $s.EndsWith("'"))) {
    $s = $s.Substring(1, $s.Length - 2)
  }
  return $s
}

function Read-EnvFile([string]$path) {
  $map = @{}
  foreach ($line in Get-Content $path) {
    $trim = $line.Trim()
    if (-not $trim) { continue }
    if ($trim.StartsWith("#")) { continue }

    $idx = $trim.IndexOf("=")
    if ($idx -lt 1) { continue }

    $key   = $trim.Substring(0, $idx).Trim()
    $value = $trim.Substring($idx + 1)

    $map[$key] = (Normalize-EnvValue $value)
  }
  return $map
}

# ★ mall build target
$BuildTarget = "./cmd/mall"

# ------------------------------------------------------------
# 0) gcloud のプロジェクト確認
# ------------------------------------------------------------
$ProjectId = (gcloud config get-value project 2>$null).Trim()
if (-not $ProjectId) {
  throw "gcloud config project is not set. Example: gcloud config set project <YOUR_PROJECT_ID>"
}
Write-Step "Using project: $ProjectId"

$RunServiceAccount = "narratives-backend-sa@$ProjectId.iam.gserviceaccount.com"

$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$SourceDir = $ScriptDir

# ------------------------------------------------------------
# 1) Go build チェック
# ------------------------------------------------------------
$MainGo = Join-Path $SourceDir "cmd\mall\main.go"
if (-not (Test-Path $MainGo)) {
  throw "Go main file not found: $MainGo"
}

Write-Step "go build check (cmd/mall)"
Push-Location $SourceDir
try {
  go version | Out-Null
  go build ./cmd/mall
} finally {
  Pop-Location
}
Write-Ok "go build succeeded"

# ------------------------------------------------------------
# 2) Artifact Registry リポジトリ確認
# ------------------------------------------------------------
Write-Step "Ensuring Artifact Registry repository: ${RepoName}"
$repoExists = $true
try {
  gcloud artifacts repositories describe $RepoName --location=$Region --project=$ProjectId | Out-Null
} catch {
  $repoExists = $false
}

if (-not $repoExists) {
  Write-Warn "Repository '${RepoName}' not found. Creating it..."
  gcloud artifacts repositories create $RepoName `
    --repository-format=docker `
    --location=$Region `
    --description="Backend images for ${ServiceName}" `
    --project=$ProjectId | Out-Null
  Write-Ok "Repository created: ${RepoName}"
} else {
  Write-Ok "Repository exists: ${RepoName}"
}

# ------------------------------------------------------------
# 3) イメージ名決定
# ------------------------------------------------------------
$AutoGenerated = $false
if ([string]::IsNullOrWhiteSpace($Image)) {
  $RegistryHost = "${Region}-docker.pkg.dev"
  $Tag = Get-Date -Format "yyyyMMdd-HHmmss"
  $Image = "${RegistryHost}/${ProjectId}/${RepoName}/${ServiceName}:${Tag}"
  $AutoGenerated = $true
  Write-Step "No image specified. Generated image: $Image"
} else {
  Write-Step "Using specified image: $Image"
}

$Dockerfile = Join-Path $SourceDir "Dockerfile"
if (-not (Test-Path $Dockerfile)) {
  throw "Dockerfile not found: $Dockerfile"
}
Write-Step "Using Dockerfile: $Dockerfile"

# ------------------------------------------------------------
# 4) ビルド & push (Podman 優先 / Cloud Build fallback)
# ------------------------------------------------------------
function Try-StartPodmanMachine {
  try { podman machine start | Out-Null } catch { }
}

function Test-PodmanAvailable {
  try { podman info | Out-Null; return $true } catch {
    Try-StartPodmanMachine
    try { podman info | Out-Null; return $true } catch { return $false }
  }
}

function Configure-ArtifactRegistryAuthForPodman([string]$RegistryHost) {
  Write-Step "Logging in to Artifact Registry (Podman): ${RegistryHost}"
  $token = (gcloud auth print-access-token --project $ProjectId 2>$null).Trim()
  if (-not $token) {
    throw "Failed to obtain access token. Run: gcloud auth login  (and/or) gcloud auth application-default login"
  }
  $token | podman login $RegistryHost --username "oauth2accesstoken" --password-stdin | Out-Null
  if ($LASTEXITCODE -ne 0) { throw "podman login failed with exit code $LASTEXITCODE" }
  Write-Ok "Podman registry login succeeded"
}

function New-CloudBuildConfig([string]$path, [string]$image, [string]$buildTarget) {
@"
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build','-t','${image}','--build-arg','BUILD_TARGET=${buildTarget}','.']
images:
- '${image}'
"@ | Set-Content -Path $path -Encoding UTF8
}

if ($AutoGenerated) {
  $PodmanAvailable = $false
  if ($PreferPodmanWhenAvailable) { $PodmanAvailable = Test-PodmanAvailable }

  if ($PodmanAvailable) {
    Write-Step "Podman detected. Using local podman build & push"
    $RegistryHost = "${Region}-docker.pkg.dev"
    Configure-ArtifactRegistryAuthForPodman $RegistryHost

    Push-Location $SourceDir
    try {
      podman build -t "$Image" --build-arg "BUILD_TARGET=$BuildTarget" -f "$Dockerfile" .
      if ($LASTEXITCODE -ne 0) { throw "podman build failed with exit code $LASTEXITCODE" }

      podman push "$Image"
      if ($LASTEXITCODE -ne 0) { throw "podman push failed with exit code $LASTEXITCODE" }
    } finally {
      Pop-Location
    }
    Write-Ok "Image build & push completed (Podman)"
  } else {
    Write-Step "Podman not available. Using Cloud Build"
    $tmp = Join-Path $env:TEMP ("cloudbuild-mall-{0}.yaml" -f (Get-Date -Format "yyyyMMdd-HHmmss"))
    New-CloudBuildConfig $tmp $Image $BuildTarget
    gcloud builds submit --config "$tmp" --project "$ProjectId" "$SourceDir"
    if ($LASTEXITCODE -ne 0) { throw "Cloud Build failed. exit code: $LASTEXITCODE" }
    Remove-Item "$tmp" -ErrorAction SilentlyContinue
    Write-Ok "Image build & push completed (Cloud Build)"
  }
} else {
  Write-Warn "Auto-image disabled (explicit -Image). Skipping build/push."
}

# ------------------------------------------------------------
# 5) Cloud Run env vars
# ------------------------------------------------------------
Write-Step "Collecting env vars for Cloud Run"

$AllowedKeys = @(
  "GCP_PROJECT_ID","FIREBASE_PROJECT_ID","FIRESTORE_PROJECT_ID",
  "SENDGRID_API_KEY","SENDGRID_FROM","CONSOLE_BASE_URL",
  "SOLANA_RPC_URL","SOLANA_MINT_KEY_SECRET",
  "ARWEAVE_BASE_URL",
  "TOKEN_ICON_BUCKET","TOKEN_CONTENTS_BUCKET",
  "LIST_BUCKET",
  "AVATAR_ICON_BUCKET",
  "TOKEN_ICON_SIGNER_EMAIL","GCS_SIGNER_EMAIL",
  "AVATAR_ICON_SIGNER_EMAIL",
  "SELF_BASE_URL"
)

$envMap = @{}
$envMap["GOOGLE_CLOUD_PROJECT"] = $ProjectId

$EnvFile = Join-Path $SourceDir ".env"
if (Test-Path $EnvFile) {
  Write-Ok "Found .env: $EnvFile"
  $fileMap = Read-EnvFile $EnvFile
  foreach ($k in $AllowedKeys) {
    if ($fileMap.ContainsKey($k)) { $envMap[$k] = $fileMap[$k] }
  }
} else {
  Write-Warn ".env file not found at $EnvFile. Will only set GOOGLE_CLOUD_PROJECT and project-id defaults."
}

if (-not $envMap.ContainsKey("GCP_PROJECT_ID"))       { $envMap["GCP_PROJECT_ID"] = $ProjectId }
if (-not $envMap.ContainsKey("FIREBASE_PROJECT_ID"))  { $envMap["FIREBASE_PROJECT_ID"] = $ProjectId }
if (-not $envMap.ContainsKey("FIRESTORE_PROJECT_ID")) { $envMap["FIRESTORE_PROJECT_ID"] = $ProjectId }

if (-not $envMap.ContainsKey("AVATAR_ICON_BUCKET")) {
  $envMap["AVATAR_ICON_BUCKET"] = "narratives-development_avatar_icon"
}

if (-not $envMap.ContainsKey("AVATAR_ICON_SIGNER_EMAIL")) {
  if ($envMap.ContainsKey("GCS_SIGNER_EMAIL") -and $envMap["GCS_SIGNER_EMAIL"].Trim()) {
    $envMap["AVATAR_ICON_SIGNER_EMAIL"] = $envMap["GCS_SIGNER_EMAIL"]
  } elseif ($envMap.ContainsKey("TOKEN_ICON_SIGNER_EMAIL") -and $envMap["TOKEN_ICON_SIGNER_EMAIL"].Trim()) {
    $envMap["AVATAR_ICON_SIGNER_EMAIL"] = $envMap["TOKEN_ICON_SIGNER_EMAIL"]
  } else {
    $envMap["AVATAR_ICON_SIGNER_EMAIL"] = $RunServiceAccount
  }
}

if (-not $envMap.ContainsKey("SELF_BASE_URL") -or [string]::IsNullOrWhiteSpace($envMap["SELF_BASE_URL"])) {
  try {
    $selfUrl = (gcloud run services describe $ServiceName `
      --region $Region `
      --project $ProjectId `
      --format "value(status.url)" 2>$null).Trim()
    if ($selfUrl) {
      $envMap["SELF_BASE_URL"] = $selfUrl.TrimEnd("/")
      Write-Ok "SELF_BASE_URL resolved from Cloud Run: $($envMap["SELF_BASE_URL"])"
    } else {
      Write-Warn "SELF_BASE_URL could not be resolved (service url empty). Please set it in .env."
    }
  } catch {
    Write-Warn "Failed to resolve SELF_BASE_URL from Cloud Run. Please set it in .env."
  }
}

$envPairs = @()
foreach ($k in $envMap.Keys) {
  $v = $envMap[$k]
  if ($null -eq $v) { $v = "" }
  $envPairs += "$k=$v"
}
$envArg = [string]::Join(",", $envPairs)

Write-Step "Env vars to update: $envArg"

# ------------------------------------------------------------
# 6) Cloud Run deploy
# ------------------------------------------------------------
Write-Step "Deploying to Cloud Run (mall)"

$deployArgs = @(
  "run","deploy", $ServiceName,
  "--image",           $Image,
  "--region",          $Region,
  "--platform",        "managed",
  "--allow-unauthenticated",
  "--service-account", $RunServiceAccount,
  "--update-env-vars", $envArg,
  "--min-instances",   "0",
  "--max-instances",   "5",
  "--memory",          "512Mi",
  "--cpu",             "1",
  "--concurrency",     "80",
  "--timeout",         "60s",
  "--project",         $ProjectId
)

& gcloud @deployArgs
if ($LASTEXITCODE -ne 0) { throw "gcloud run deploy failed. exit code: $LASTEXITCODE" }

Write-Ok "Cloud Run deployment finished: service '${ServiceName}'"
if ($AutoGenerated) { Write-Ok "Deployed with image: ${Image}" }
