# backend\deploy-backend.ps1
param(
  # Example explicit image: asia-northeast1-docker.pkg.dev/<PROJECT>/<REPO>/<SERVICE>:<TAG>
  [string]$Image,

  # Region / Cloud Run service name
  [string]$Region      = "asia-northeast1",
  [string]$ServiceName = "narratives-backend",

  # Artifact Registry repository name (Docker)
  [string]$RepoName    = "narratives-backend",

  # If -Image is auto-generated and Docker is available, use local docker build/push.
  # If Docker is unavailable, fallback to Cloud Build automatically.
  [bool]$PreferDockerWhenAvailable = $true
)

$ErrorActionPreference = "Stop"

function Write-Step($msg) { Write-Host "== $msg ==" -ForegroundColor Cyan }
function Write-Ok($msg)   { Write-Host "OK: $msg" -ForegroundColor Green }
function Write-Warn($msg) { Write-Host "!! $msg" -ForegroundColor Yellow }

function Normalize-EnvValue([string]$v) {
  if ($null -eq $v) { return "" }
  $s = $v.Trim()
  # strip surrounding quotes
  if (($s.StartsWith('"') -and $s.EndsWith('"')) -or ($s.StartsWith("'") -and $s.EndsWith("'"))) {
    $s = $s.Substring(1, $s.Length - 2)
  }
  return $s
}

function Read-EnvFile([string]$path) {
  $map = @{}
  foreach ($line in Get-Content $path) {
    $trim = $line.Trim()
    if (-not $trim) { continue }            # empty
    if ($trim.StartsWith("#")) { continue } # comment

    $idx = $trim.IndexOf("=")
    if ($idx -lt 1) { continue }

    $key   = $trim.Substring(0, $idx).Trim()
    $value = $trim.Substring($idx + 1)

    $map[$key] = (Normalize-EnvValue $value)
  }
  return $map
}

# ------------------------------------------------------------
# 0) gcloud のプロジェクト確認
# ------------------------------------------------------------
$ProjectId = (gcloud config get-value project 2>$null).Trim()
if (-not $ProjectId) {
  throw "gcloud config project is not set. Example: gcloud config set project <YOUR_PROJECT_ID>"
}
Write-Step "Using project: $ProjectId"

# Cloud Run service account
$RunServiceAccount = "narratives-backend-sa@$ProjectId.iam.gserviceaccount.com"

# スクリプト / ソースディレクトリ
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$SourceDir = $ScriptDir

# ------------------------------------------------------------
# 1) Go build チェック
# ------------------------------------------------------------
$MainGo = Join-Path $SourceDir "cmd\api\main.go"
if (-not (Test-Path $MainGo)) {
  throw "Go main file not found: $MainGo"
}

Write-Step "go build check (cmd/api)"
Push-Location $SourceDir
try {
  go version | Out-Null
  go build ./cmd/api
} finally {
  Pop-Location
}
Write-Ok "go build succeeded"

# ------------------------------------------------------------
# 2) Artifact Registry リポジトリ確認
# ------------------------------------------------------------
Write-Step "Ensuring Artifact Registry repository: ${RepoName}"
$repoExists = $true
try {
  gcloud artifacts repositories describe $RepoName --location=$Region --project=$ProjectId | Out-Null
} catch {
  $repoExists = $false
}

if (-not $repoExists) {
  Write-Warn "Repository '${RepoName}' not found. Creating it..."
  gcloud artifacts repositories create $RepoName `
    --repository-format=docker `
    --location=$Region `
    --description="Backend images for ${ServiceName}" `
    --project=$ProjectId | Out-Null
  Write-Ok "Repository created: ${RepoName}"
} else {
  Write-Ok "Repository exists: ${RepoName}"
}

# ------------------------------------------------------------
# 3) イメージ名決定
# ------------------------------------------------------------
$AutoGenerated = $false
if ([string]::IsNullOrWhiteSpace($Image)) {
  $RegistryHost = "${Region}-docker.pkg.dev"
  $Tag = Get-Date -Format "yyyyMMdd-HHmmss"
  $Image = "${RegistryHost}/${ProjectId}/${RepoName}/${ServiceName}:${Tag}"
  $AutoGenerated = $true
  Write-Step "No image specified. Generated image: $Image"
} else {
  Write-Step "Using specified image: $Image"
}

# ------------------------------------------------------------
# 4) ビルド & push (Docker 優先)
# ------------------------------------------------------------
function Test-DockerAvailable {
  try {
    docker info | Out-Null
    return $true
  } catch {
    return $false
  }
}

if ($AutoGenerated) {
  $DockerAvailable = $false
  if ($PreferDockerWhenAvailable) {
    $DockerAvailable = Test-DockerAvailable
  }

  if ($DockerAvailable) {
    Write-Step "Docker detected. Using local docker build & push"

    $RegistryHost = "${Region}-docker.pkg.dev"
    Write-Step "Configuring Docker auth for ${RegistryHost}"
    gcloud auth configure-docker "$RegistryHost" -q | Out-Null
    Write-Ok "Docker auth configured"

    Push-Location $SourceDir
    try {
      docker build -t "$Image" .
      if ($LASTEXITCODE -ne 0) { throw "docker build failed with exit code $LASTEXITCODE" }
      docker push "$Image"
      if ($LASTEXITCODE -ne 0) { throw "docker push failed with exit code $LASTEXITCODE" }
    } finally {
      Pop-Location
    }
    Write-Ok "Image build & push completed (Docker)"
  } else {
    Write-Step "Docker not available. Using Cloud Build"
    gcloud builds submit --tag "$Image" --project "$ProjectId"
    if ($LASTEXITCODE -ne 0) {
      throw "Cloud Build failed. exit code: $LASTEXITCODE"
    }
    Write-Ok "Image build & push completed (Cloud Build)"
  }
} else {
  Write-Warn "Auto-image disabled (explicit -Image). Skipping build/push."
}

# ------------------------------------------------------------
# 5) Cloud Run に渡す環境変数を組み立てる
#    - backend/.env から「バックエンド用キーだけ」拾う
#    - TOKEN_ICON_* / TOKEN_CONTENTS_BUCKET / LIST_BUCKET / AVATAR_ICON_* を追加
#    - 注意: ここは --update-env-vars を使い、既存 env を不用意に消さない
# ------------------------------------------------------------
Write-Step "Collecting env vars for Cloud Run"

# Cloud Run に渡したいキー（あなたの .env 内容に合わせて）
$AllowedKeys = @(
  # Project / Firestore
  "GCP_PROJECT_ID",
  "FIREBASE_PROJECT_ID",
  "FIRESTORE_PROJECT_ID",

  # SendGrid
  "SENDGRID_API_KEY",
  "SENDGRID_FROM",
  "CONSOLE_BASE_URL",

  # Solana
  "SOLANA_RPC_URL",
  "SOLANA_MINT_KEY_SECRET",

  # Arweave / Irys
  "ARWEAVE_BASE_URL",

  # GCS buckets
  "TOKEN_ICON_BUCKET",
  "TOKEN_CONTENTS_BUCKET",

  # ✅ NEW: List images bucket
  "LIST_BUCKET",

  # ✅ NEW: Avatar icon bucket (Signed URL)
  "AVATAR_ICON_BUCKET",

  # Signed URL signer email
  "TOKEN_ICON_SIGNER_EMAIL",
  "GCS_SIGNER_EMAIL",

  # ✅ NEW: Avatar icon signer email
  "AVATAR_ICON_SIGNER_EMAIL"
)

# まず必ずセットするもの（GOOGLE_CLOUD_PROJECT はランタイムで参照しがち）
$envMap = @{}
$envMap["GOOGLE_CLOUD_PROJECT"] = $ProjectId

# backend/.env を読む想定
$EnvFile = Join-Path $SourceDir ".env"
if (Test-Path $EnvFile) {
  Write-Ok "Found .env: $EnvFile"
  $fileMap = Read-EnvFile $EnvFile

  foreach ($k in $AllowedKeys) {
    if ($fileMap.ContainsKey($k)) {
      $envMap[$k] = $fileMap[$k]
    }
  }
} else {
  Write-Warn ".env file not found at $EnvFile. Will only set GOOGLE_CLOUD_PROJECT and project-id defaults."
}

# .env に無い場合でも、最低限プロジェクトID系は揃える（container.go が参照する想定の保険）
if (-not $envMap.ContainsKey("GCP_PROJECT_ID"))       { $envMap["GCP_PROJECT_ID"] = $ProjectId }
if (-not $envMap.ContainsKey("FIREBASE_PROJECT_ID"))  { $envMap["FIREBASE_PROJECT_ID"] = $ProjectId }
if (-not $envMap.ContainsKey("FIRESTORE_PROJECT_ID")) { $envMap["FIRESTORE_PROJECT_ID"] = $ProjectId }

# ✅ NEW: Avatar icon bucket defaults（.env が無くても動く保険）
if (-not $envMap.ContainsKey("AVATAR_ICON_BUCKET")) {
  $envMap["AVATAR_ICON_BUCKET"] = "narratives-development_avatar_icon"
}

# ✅ NEW: Avatar icon signer email defaults
# - まず .env の AVATAR_ICON_SIGNER_EMAIL を優先
# - 無ければ GCS_SIGNER_EMAIL / TOKEN_ICON_SIGNER_EMAIL を流用
# - 最後に Cloud Run runtime SA を保険として入れる
if (-not $envMap.ContainsKey("AVATAR_ICON_SIGNER_EMAIL")) {
  if ($envMap.ContainsKey("GCS_SIGNER_EMAIL") -and $envMap["GCS_SIGNER_EMAIL"].Trim()) {
    $envMap["AVATAR_ICON_SIGNER_EMAIL"] = $envMap["GCS_SIGNER_EMAIL"]
  } elseif ($envMap.ContainsKey("TOKEN_ICON_SIGNER_EMAIL") -and $envMap["TOKEN_ICON_SIGNER_EMAIL"].Trim()) {
    $envMap["AVATAR_ICON_SIGNER_EMAIL"] = $envMap["TOKEN_ICON_SIGNER_EMAIL"]
  } else {
    $envMap["AVATAR_ICON_SIGNER_EMAIL"] = $RunServiceAccount
  }
}

# Cloud Run 用 "k=v,k=v" にする（値にカンマが入るケースは想定外）
$envPairs = @()
foreach ($k in $envMap.Keys) {
  $v = $envMap[$k]
  if ($null -eq $v) { $v = "" }
  $envPairs += "$k=$v"
}
$envArg = [string]::Join(",", $envPairs)

Write-Step "Env vars to update: $envArg"

# ------------------------------------------------------------
# 6) Cloud Run へデプロイ
# ------------------------------------------------------------
Write-Step "Deploying to Cloud Run"

$deployArgs = @(
  "run","deploy", $ServiceName,
  "--image",           $Image,
  "--region",          $Region,
  "--platform",        "managed",
  "--allow-unauthenticated",
  "--service-account", $RunServiceAccount,

  # ★重要: 既存 env を消さずに「追加/更新」する
  "--update-env-vars", $envArg,

  "--min-instances",   "0",
  "--max-instances",   "5",
  "--memory",          "512Mi",
  "--cpu",             "1",
  "--concurrency",     "80",
  "--timeout",         "60s",
  "--project",         $ProjectId
)

& gcloud @deployArgs
if ($LASTEXITCODE -ne 0) {
  throw "gcloud run deploy failed. exit code: $LASTEXITCODE"
}

Write-Ok "Cloud Run deployment finished: service '${ServiceName}'"
if ($AutoGenerated) {
  Write-Ok "Deployed with image: ${Image}"
}
