// frontend/member/src/infrastructure/mock/mockdata.tsx

import type { Member } from "../../../../shell/src/shared/types/member";

export const MOCK_MEMBERS: Member[] = [
  {
    id: "mem-001",
    lastName: "小林",
    firstName: "静香",
    lastNameKana: "コバヤシ",
    firstNameKana: "シズカ",
    email: "designer.lumina@narratives.com",
    permissions: ["view_products", "manage_product_blueprints"],
    assignedBrands: ["lumina-fashion"],
    createdAt: "2024-06-25T00:00:00Z",
  },
  {
    id: "mem-002",
    lastName: "渡辺",
    firstName: "花子",
    lastNameKana: "ワタナベ",
    firstNameKana: "ハナコ",
    email: "support.lumina@narratives.com",
    permissions: ["view_inquiries", "respond_inquiries"],
    assignedBrands: ["lumina-fashion"],
    createdAt: "2024-06-15T00:00:00Z",
  },
  {
    id: "mem-003",
    lastName: "中村",
    firstName: "拓也",
    lastNameKana: "ナカムラ",
    firstNameKana: "タクヤ",
    email: "token.lumina@narratives.com",
    permissions: ["view_tokens", "mint_tokens", "burn_tokens"],
    assignedBrands: ["lumina-fashion"],
    createdAt: "2024-04-18T00:00:00Z",
  },
  {
    id: "mem-004",
    lastName: "伊藤",
    firstName: "愛子",
    lastNameKana: "イトウ",
    firstNameKana: "アイコ",
    email: "support.nexus@narratives.com",
    permissions: ["view_inquiries", "respond_inquiries"],
    assignedBrands: ["nexus-street"],
    createdAt: "2024-04-05T00:00:00Z",
  },
  {
    id: "mem-005",
    lastName: "田中",
    firstName: "雄太",
    lastNameKana: "タナカ",
    firstNameKana: "ユウタ",
    email: "marketing.nexus@narratives.com",
    permissions: [
      "view_members",
      "manage_members",
      "view_brands",
      "manage_brands",
    ],
    assignedBrands: ["nexus-street"],
    createdAt: "2024-03-22T00:00:00Z",
  },
  {
    id: "mem-006",
    lastName: "高橋",
    firstName: "健太",
    lastNameKana: "タカハシ",
    firstNameKana: "ケンタ",
    email: "token.nexus@narratives.com",
    permissions: ["view_tokens", "mint_tokens", "burn_tokens"],
    assignedBrands: ["nexus-street"],
    createdAt: "2024-03-10T00:00:00Z",
  },
  {
    id: "mem-007",
    lastName: "松本",
    firstName: "葵",
    lastNameKana: "マツモト",
    firstNameKana: "アオイ",
    email: "designer.nexus@narratives.com",
    permissions: ["view_products", "manage_product_blueprints"],
    assignedBrands: ["nexus-street"],
    createdAt: "2024-03-05T00:00:00Z",
  },
  {
    id: "mem-008",
    lastName: "佐藤",
    firstName: "美咲",
    lastNameKana: "サトウ",
    firstNameKana: "ミサキ",
    email: "manager.lumina@narratives.com",
    permissions: [
      "view_members",
      "manage_members",
      "view_brands",
      "manage_brands",
    ],
    assignedBrands: ["lumina-fashion"],
    createdAt: "2024-02-20T00:00:00Z",
  },
  {
    id: "mem-009",
    lastName: "山田",
    firstName: "太郎",
    lastNameKana: "ヤマダ",
    firstNameKana: "タロウ",
    email: "admin@narratives.com",
    permissions: [
      "view_members",
      "manage_members",
      "view_brands",
      "manage_brands",
      "view_products",
      "manage_product_blueprints",
      "view_tokens",
      "mint_tokens",
      "burn_tokens",
      "view_inquiries",
      "respond_inquiries",
      "manage_permissions",
    ],
    assignedBrands: ["lumina-fashion", "nexus-street"],
    createdAt: "2024-01-15T00:00:00Z",
  },
];
