// backend/internal/domain/message/entity.go
package message

import (
	"errors"
	"strings"
	"time"

	avatarstate "narratives/internal/domain/avatarState"
)

// Message represents a direct message between avatars.
// A message is allowed when the recipient is either:
// - in senderState.Following: an avatar the sender follows
// - in senderState.Followers: an avatar following the sender
type Message struct {
	ID               string                   `json:"id"`
	SenderAvatarID   string                   `json:"senderAvatarId"`
	ReceiverAvatarID string                   `json:"receiverAvatarId"`
	Body             string                   `json:"body,omitempty"`
	Images           []MessageImageAttachment `json:"images,omitempty"`
	IsRead           bool                     `json:"isRead"`
	ReadAt           *time.Time               `json:"readAt,omitempty"`
	CreatedAt        time.Time                `json:"createdAt"`
	UpdatedAt        time.Time                `json:"updatedAt"`
}

// MessageImageAttachment represents an image stored in Firebase Storage.
// StoragePath is the source of truth. DownloadURL is optional because it may be
// generated by infrastructure/application layers.
type MessageImageAttachment struct {
	StoragePath string    `json:"storagePath"`
	DownloadURL *string   `json:"downloadUrl,omitempty"`
	ContentType string    `json:"contentType"`
	SizeBytes   int64     `json:"sizeBytes"`
	Width       *int64    `json:"width,omitempty"`
	Height      *int64    `json:"height,omitempty"`
	UploadedAt  time.Time `json:"uploadedAt"`
}

// Policy
var (
	MaxBodyLength             = 5000
	MaxImageAttachmentCount   = 4
	MaxImageStoragePathLength = 1024
	MaxImageDownloadURLLength = 2048
	MaxImageSizeBytes         = int64(10 * 1024 * 1024)
)

// Errors
var (
	ErrInvalidID               = errors.New("message: invalid id")
	ErrInvalidSenderAvatarID   = errors.New("message: invalid senderAvatarId")
	ErrInvalidReceiverAvatarID = errors.New("message: invalid receiverAvatarId")
	ErrSelfMessageNotAllowed   = errors.New("message: self message is not allowed")
	ErrInvalidBody             = errors.New("message: invalid body")
	ErrEmptyMessage            = errors.New("message: body or image is required")
	ErrInvalidReadAt           = errors.New("message: invalid readAt")
	ErrInvalidCreatedAt        = errors.New("message: invalid createdAt")
	ErrInvalidUpdatedAt        = errors.New("message: invalid updatedAt")
	ErrMessageNotAllowed       = errors.New("message: receiver is not follower or following")

	ErrTooManyImages           = errors.New("message: too many images")
	ErrInvalidImageStoragePath = errors.New("message: invalid image storagePath")
	ErrInvalidImageDownloadURL = errors.New("message: invalid image downloadUrl")
	ErrInvalidImageContentType = errors.New("message: invalid image contentType")
	ErrInvalidImageSize        = errors.New("message: invalid image sizeBytes")
	ErrInvalidImageDimensions  = errors.New("message: invalid image dimensions")
	ErrInvalidImageUploadedAt  = errors.New("message: invalid image uploadedAt")
	ErrDuplicateImage          = errors.New("message: duplicate image storagePath")
)

// Constructors

func New(
	id, senderAvatarID, receiverAvatarID, body string,
	images []MessageImageAttachment,
	isRead bool,
	readAt *time.Time,
	createdAt, updatedAt time.Time,
) (Message, error) {
	var readAtUTC *time.Time
	if readAt != nil {
		t := readAt.UTC()
		readAtUTC = &t
	}

	m := Message{
		ID:               id,
		SenderAvatarID:   senderAvatarID,
		ReceiverAvatarID: receiverAvatarID,
		Body:             body,
		Images:           normalizeImageTimes(images),
		IsRead:           isRead,
		ReadAt:           readAtUTC,
		CreatedAt:        createdAt.UTC(),
		UpdatedAt:        updatedAt.UTC(),
	}

	if err := m.validate(); err != nil {
		return Message{}, err
	}
	return m, nil
}

func NewForCreate(
	id, senderAvatarID, receiverAvatarID, body string,
	images []MessageImageAttachment,
	senderState avatarstate.AvatarState,
	now time.Time,
) (Message, error) {
	if err := ValidateMessageRelation(senderState, senderAvatarID, receiverAvatarID); err != nil {
		return Message{}, err
	}

	now = now.UTC()
	return New(
		id,
		senderAvatarID,
		receiverAvatarID,
		body,
		images,
		false,
		nil,
		now,
		now,
	)
}

// Mutators

func (m *Message) MarkAsRead(readAt time.Time) error {
	readAt = readAt.UTC()

	if readAt.IsZero() || readAt.Before(m.CreatedAt) {
		return ErrInvalidReadAt
	}

	m.IsRead = true
	m.ReadAt = &readAt
	m.UpdatedAt = readAt
	return nil
}

func (m *Message) UpdateBody(body string, updatedAt time.Time) error {
	if body == "" || len([]rune(body)) > MaxBodyLength {
		return ErrInvalidBody
	}

	updatedAt = updatedAt.UTC()
	if updatedAt.IsZero() || updatedAt.Before(m.CreatedAt) {
		return ErrInvalidUpdatedAt
	}

	m.Body = body
	m.UpdatedAt = updatedAt
	return nil
}

func (m *Message) SetImages(images []MessageImageAttachment, updatedAt time.Time) error {
	updatedAt = updatedAt.UTC()
	if updatedAt.IsZero() || updatedAt.Before(m.CreatedAt) {
		return ErrInvalidUpdatedAt
	}

	images = normalizeImageTimes(images)
	if err := validateImages(images); err != nil {
		return err
	}
	if m.Body == "" && len(images) == 0 {
		return ErrEmptyMessage
	}

	m.Images = images
	m.UpdatedAt = updatedAt
	return nil
}

// Validation

func (m Message) validate() error {
	if m.ID == "" {
		return ErrInvalidID
	}
	if m.SenderAvatarID == "" {
		return ErrInvalidSenderAvatarID
	}
	if m.ReceiverAvatarID == "" {
		return ErrInvalidReceiverAvatarID
	}
	if m.SenderAvatarID == m.ReceiverAvatarID {
		return ErrSelfMessageNotAllowed
	}
	if len([]rune(m.Body)) > MaxBodyLength {
		return ErrInvalidBody
	}
	if m.Body == "" && len(m.Images) == 0 {
		return ErrEmptyMessage
	}
	if err := validateImages(m.Images); err != nil {
		return err
	}
	if m.CreatedAt.IsZero() {
		return ErrInvalidCreatedAt
	}
	if m.UpdatedAt.IsZero() || m.UpdatedAt.Before(m.CreatedAt) {
		return ErrInvalidUpdatedAt
	}
	if m.ReadAt != nil {
		if m.ReadAt.IsZero() || m.ReadAt.Before(m.CreatedAt) {
			return ErrInvalidReadAt
		}
		if !m.IsRead {
			return ErrInvalidReadAt
		}
	}

	return nil
}

func validateImages(images []MessageImageAttachment) error {
	if len(images) > MaxImageAttachmentCount {
		return ErrTooManyImages
	}

	paths := make(map[string]struct{}, len(images))
	for _, img := range images {
		if img.StoragePath == "" || len([]rune(img.StoragePath)) > MaxImageStoragePathLength {
			return ErrInvalidImageStoragePath
		}
		if _, exists := paths[img.StoragePath]; exists {
			return ErrDuplicateImage
		}
		paths[img.StoragePath] = struct{}{}

		if img.DownloadURL != nil && len([]rune(*img.DownloadURL)) > MaxImageDownloadURLLength {
			return ErrInvalidImageDownloadURL
		}
		if !isValidImageContentType(img.ContentType) {
			return ErrInvalidImageContentType
		}
		if img.SizeBytes <= 0 || img.SizeBytes > MaxImageSizeBytes {
			return ErrInvalidImageSize
		}
		if img.Width != nil && *img.Width <= 0 {
			return ErrInvalidImageDimensions
		}
		if img.Height != nil && *img.Height <= 0 {
			return ErrInvalidImageDimensions
		}
		if img.UploadedAt.IsZero() {
			return ErrInvalidImageUploadedAt
		}
	}

	return nil
}

func isValidImageContentType(contentType string) bool {
	switch strings.ToLower(contentType) {
	case "image/jpeg", "image/png", "image/webp", "image/gif":
		return true
	default:
		return false
	}
}

func normalizeImageTimes(images []MessageImageAttachment) []MessageImageAttachment {
	for i := range images {
		images[i].UploadedAt = images[i].UploadedAt.UTC()
	}
	return images
}

// ValidateMessageRelation checks whether receiverAvatarID is either following
// senderAvatarID or followed by senderAvatarID.
func ValidateMessageRelation(
	senderState avatarstate.AvatarState,
	senderAvatarID, receiverAvatarID string,
) error {
	if senderAvatarID == "" {
		return ErrInvalidSenderAvatarID
	}
	if receiverAvatarID == "" {
		return ErrInvalidReceiverAvatarID
	}
	if senderAvatarID == receiverAvatarID {
		return ErrSelfMessageNotAllowed
	}
	if senderState.ID != senderAvatarID {
		return ErrInvalidSenderAvatarID
	}

	if hasAvatarID(senderState.Following, receiverAvatarID) {
		return nil
	}
	if hasAvatarID(senderState.Followers, receiverAvatarID) {
		return nil
	}

	return ErrMessageNotAllowed
}

func hasAvatarID(refs []avatarstate.AvatarFollowRef, avatarID string) bool {
	for _, ref := range refs {
		if ref.AvatarID == avatarID {
			return true
		}
	}
	return false
}
