// backend/internal/application/usecase/brand_fee_settlement_usecase.go
package usecase

import (
	"context"
	"errors"
	"time"

	brandfeesettlementdom "narratives/internal/domain/brandFeeSettlement"
)

var (
	ErrBrandFeeSettlementRepositoryMissing = errors.New("brandFeeSettlement: repository is not configured")
	ErrBrandFeeSettlementClockMissing      = errors.New("brandFeeSettlement: clock is not configured")
	ErrBrandFeeSettlementExistingMismatch  = errors.New("brandFeeSettlement: existing settlement does not match requested allocation")
	ErrBrandFeeSettlementCannotReady       = errors.New("brandFeeSettlement: settlement cannot become ready")
	ErrBrandFeeSettlementCannotCancel      = errors.New("brandFeeSettlement: settlement cannot be canceled")
	ErrBrandFeeSettlementInvalidLimit      = errors.New("brandFeeSettlement: invalid list limit")
)

// ============================================================
// Transfer repository port
// ============================================================

// BrandFeeSettlementTransferRepository extends the domain repository with the
// atomic operations required by the Brand fee Stripe Transfer worker.
//
// Stripe Transfer execution must never use a plain GetByID followed by a
// non-transactional status update. ClaimForTransfer must atomically establish
// ownership of the transfer attempt.
//
// The Firestore implementation is expected to provide these methods in addition
// to brandFeeSettlement.Repository.
type BrandFeeSettlementTransferRepository interface {
	brandfeesettlementdom.Repository

	ClaimForTransfer(
		ctx context.Context,
		brandFeeSettlementID string,
		now time.Time,
		staleBefore time.Time,
	) (brandfeesettlementdom.BrandFeeSettlement, bool, error)

	CompleteTransfer(
		ctx context.Context,
		brandFeeSettlementID string,
		stripeTransferID string,
		now time.Time,
	) (brandfeesettlementdom.BrandFeeSettlement, error)

	FailTransfer(
		ctx context.Context,
		brandFeeSettlementID string,
		status brandfeesettlementdom.Status,
		errorType *string,
		errorCode *string,
		errorMsg *string,
		now time.Time,
	) (brandfeesettlementdom.BrandFeeSettlement, error)

	ReverseTransfer(
		ctx context.Context,
		brandFeeSettlementID string,
		stripeTransferReversalID string,
		now time.Time,
	) (brandfeesettlementdom.BrandFeeSettlement, error)
}

// ============================================================
// Ensure input
// ============================================================

// EnsureBrandFeeSettlementInput represents the productBlueprint Brand share
// generated by one successfully paid resale Order item.
//
// One resale Order item creates exactly one BrandFeeSettlement.
//
// Brand is the immutable payout destination captured in the Order item's
// BrandRevenueSnapshot. Current Brand or Account state must never be re-resolved
// to alter this destination.
//
// BrandFeeAmount has already been calculated by settlement.Calculator. This
// usecase does not recalculate the percentage.
//
// The resulting document ID is deterministic:
//
//	PaymentID + "_resale_brand_fee_item_" + OrderItemIndex
//
// EnsurePending is idempotent. If that document already exists, it is accepted
// only when every immutable allocation field matches exactly.
type EnsureBrandFeeSettlementInput struct {
	OrderID        string
	PaymentID      string
	OrderItemIndex int
	ResaleID       string

	Brand brandfeesettlementdom.BrandIdentity

	StripePaymentIntentID string
	StripeChargeID        string

	TransferGroup string

	BrandFeeAmount int

	Currency string
}

// ============================================================
// Usecase
// ============================================================

// BrandFeeSettlementUsecase manages the productBlueprint Brand share generated
// by consumer resale transactions.
//
// Responsibilities:
//   - create one pending BrandFeeSettlement for each successfully paid resale item
//   - guarantee idempotent payment-success processing
//   - provide authoritative reads
//   - mark the exact Brand fee ready after the fulfillment boundary
//   - cancel a Brand fee before Stripe Transfer when permitted
//
// Actual Stripe Transfer execution is intentionally separate and must use
// BrandFeeSettlementTransferRepository so transfer claims are atomic.
type BrandFeeSettlementUsecase struct {
	repo brandfeesettlementdom.Repository
	now  func() time.Time
}

func NewBrandFeeSettlementUsecase(
	repo brandfeesettlementdom.Repository,
) *BrandFeeSettlementUsecase {
	return &BrandFeeSettlementUsecase{
		repo: repo,
		now:  time.Now,
	}
}

// ============================================================
// Read
// ============================================================

// GetByID returns one persisted BrandFeeSettlement.
func (u *BrandFeeSettlementUsecase) GetByID(
	ctx context.Context,
	brandFeeSettlementID string,
) (*brandfeesettlementdom.BrandFeeSettlement, error) {
	if err := u.validateRepositoryReady(); err != nil {
		return nil, err
	}
	if brandFeeSettlementID == "" {
		return nil, brandfeesettlementdom.ErrInvalidID
	}

	settlement, err := u.repo.GetByID(ctx, brandFeeSettlementID)
	if err != nil {
		return nil, err
	}
	if settlement.ID != brandFeeSettlementID {
		return nil, brandfeesettlementdom.ErrInvalidID
	}
	if err := settlement.Validate(); err != nil {
		return nil, err
	}

	return &settlement, nil
}

// ListByPaymentID returns every item-level Brand fee associated with one
// Payment.
func (u *BrandFeeSettlementUsecase) ListByPaymentID(
	ctx context.Context,
	paymentID string,
) ([]brandfeesettlementdom.BrandFeeSettlement, error) {
	if err := u.validateRepositoryReady(); err != nil {
		return nil, err
	}
	if paymentID == "" {
		return nil, brandfeesettlementdom.ErrInvalidPaymentID
	}

	return u.repo.ListByPaymentID(ctx, paymentID)
}

// ListByOrderID returns every item-level Brand fee associated with one Order.
func (u *BrandFeeSettlementUsecase) ListByOrderID(
	ctx context.Context,
	orderID string,
) ([]brandfeesettlementdom.BrandFeeSettlement, error) {
	if err := u.validateRepositoryReady(); err != nil {
		return nil, err
	}
	if orderID == "" {
		return nil, brandfeesettlementdom.ErrInvalidOrderID
	}

	return u.repo.ListByOrderID(ctx, orderID)
}

// ListByBrandID returns Brand fee records attributable to one productBlueprint
// Brand.
func (u *BrandFeeSettlementUsecase) ListByBrandID(
	ctx context.Context,
	brandID string,
) ([]brandfeesettlementdom.BrandFeeSettlement, error) {
	if err := u.validateRepositoryReady(); err != nil {
		return nil, err
	}
	if brandID == "" {
		return nil, brandfeesettlementdom.ErrInvalidBrandID
	}

	return u.repo.ListByBrandID(ctx, brandID)
}

// ListByCompanyID returns Brand fee records attributable to one Company.
func (u *BrandFeeSettlementUsecase) ListByCompanyID(
	ctx context.Context,
	companyID string,
) ([]brandfeesettlementdom.BrandFeeSettlement, error) {
	if err := u.validateRepositoryReady(); err != nil {
		return nil, err
	}
	if companyID == "" {
		return nil, brandfeesettlementdom.ErrInvalidCompanyID
	}

	return u.repo.ListByCompanyID(ctx, companyID)
}

// ListByAccountID returns Brand fee records attributable to one immutable payout
// Account identity.
func (u *BrandFeeSettlementUsecase) ListByAccountID(
	ctx context.Context,
	accountID string,
) ([]brandfeesettlementdom.BrandFeeSettlement, error) {
	if err := u.validateRepositoryReady(); err != nil {
		return nil, err
	}
	if accountID == "" {
		return nil, brandfeesettlementdom.ErrInvalidAccountID
	}

	return u.repo.ListByAccountID(ctx, accountID)
}

// ListTransferCandidates returns records that may require a transfer task to be
// created or retried.
//
// The repository determines eligibility:
//   - ready
//   - failed_retryable
//   - stale transferring
func (u *BrandFeeSettlementUsecase) ListTransferCandidates(
	ctx context.Context,
	staleBefore time.Time,
	limit int,
) ([]brandfeesettlementdom.BrandFeeSettlement, error) {
	if err := u.validateRepositoryReady(); err != nil {
		return nil, err
	}
	if staleBefore.IsZero() {
		return nil, brandfeesettlementdom.ErrInvalidUpdatedAt
	}
	if limit <= 0 {
		return nil, ErrBrandFeeSettlementInvalidLimit
	}

	return u.repo.ListTransferCandidates(
		ctx,
		brandfeesettlementdom.ListTransferCandidatesInput{
			StaleBefore: staleBefore.UTC(),
			Limit:       limit,
		},
	)
}

// ============================================================
// Ensure pending
// ============================================================

// EnsurePending creates the BrandFeeSettlement corresponding to one successfully
// paid resale Order item.
//
// Deterministic PaymentID + OrderItemIndex identity makes this operation safe to
// repeat after payment webhook retries or partial application failures.
//
// If the document already exists, its lifecycle state is never rewound. The
// existing record is returned only when its immutable allocation exactly matches
// the requested Brand fee.
func (u *BrandFeeSettlementUsecase) EnsurePending(
	ctx context.Context,
	in EnsureBrandFeeSettlementInput,
) (*brandfeesettlementdom.BrandFeeSettlement, error) {
	if err := u.validateWriteReady(); err != nil {
		return nil, err
	}

	brandFeeSettlementID, err := brandfeesettlementdom.NewID(
		in.PaymentID,
		in.OrderItemIndex,
	)
	if err != nil {
		return nil, err
	}

	now := u.now().UTC()

	expected, err := brandfeesettlementdom.New(
		brandFeeSettlementID,
		in.OrderID,
		in.PaymentID,
		in.OrderItemIndex,
		in.ResaleID,
		in.Brand,
		in.StripePaymentIntentID,
		in.StripeChargeID,
		in.TransferGroup,
		in.BrandFeeAmount,
		in.Currency,
		now,
	)
	if err != nil {
		return nil, err
	}

	created, err := u.repo.Create(
		ctx,
		brandfeesettlementdom.CreateBrandFeeSettlementInput{
			BrandFeeSettlementID:  brandFeeSettlementID,
			OrderID:               in.OrderID,
			PaymentID:             in.PaymentID,
			OrderItemIndex:        in.OrderItemIndex,
			ResaleID:              in.ResaleID,
			Brand:                 in.Brand,
			StripePaymentIntentID: in.StripePaymentIntentID,
			StripeChargeID:        in.StripeChargeID,
			TransferGroup:         in.TransferGroup,
			BrandFeeAmount:        in.BrandFeeAmount,
			Currency:              in.Currency,
			Status:                brandfeesettlementdom.StatusPending,
		},
	)
	if err == nil {
		if err := validateCreatedBrandFeeSettlement(created, expected); err != nil {
			return nil, err
		}

		return &created, nil
	}
	if !errors.Is(err, brandfeesettlementdom.ErrConflict) {
		return nil, err
	}

	existing, getErr := u.repo.GetByID(ctx, brandFeeSettlementID)
	if getErr != nil {
		return nil, getErr
	}
	if err := validateExistingBrandFeeSettlementAllocation(existing, expected); err != nil {
		return nil, err
	}

	return &existing, nil
}

// ============================================================
// Fulfillment boundary
// ============================================================

// MarkReady transitions one pending BrandFeeSettlement to ready after the exact
// resale Order item crosses the fulfillment boundary.
//
// Repeated execution is idempotent after the boundary has already been crossed.
// A canceled Brand fee cannot be reopened.
func (u *BrandFeeSettlementUsecase) MarkReady(
	ctx context.Context,
	brandFeeSettlementID string,
) (*brandfeesettlementdom.BrandFeeSettlement, error) {
	if err := u.validateWriteReady(); err != nil {
		return nil, err
	}
	if brandFeeSettlementID == "" {
		return nil, brandfeesettlementdom.ErrInvalidID
	}

	current, err := u.repo.GetByID(ctx, brandFeeSettlementID)
	if err != nil {
		return nil, err
	}
	if err := current.Validate(); err != nil {
		return nil, err
	}

	switch current.Status {
	case brandfeesettlementdom.StatusPending:
		nextStatus := brandfeesettlementdom.StatusReady
		updated, err := u.repo.UpdateByID(
			ctx,
			brandFeeSettlementID,
			brandfeesettlementdom.UpdateBrandFeeSettlementInput{
				Status: &nextStatus,
			},
		)
		if err != nil {
			return nil, err
		}
		if err := updated.Validate(); err != nil {
			return nil, err
		}

		return &updated, nil

	case brandfeesettlementdom.StatusReady,
		brandfeesettlementdom.StatusTransferring,
		brandfeesettlementdom.StatusTransferred,
		brandfeesettlementdom.StatusFailedRetryable,
		brandfeesettlementdom.StatusFailed,
		brandfeesettlementdom.StatusReversed:
		return &current, nil

	case brandfeesettlementdom.StatusCanceled:
		return nil, ErrBrandFeeSettlementCannotReady

	default:
		return nil, brandfeesettlementdom.ErrInvalidStatus
	}
}

// ============================================================
// Cancellation
// ============================================================

// Cancel cancels a Brand fee before a successful Stripe Transfer.
//
// pending, ready, and failed_retryable may become canceled according to the
// domain lifecycle.
//
// A repeated cancellation is idempotent.
//
// transferring cannot be canceled because the Stripe request result must first
// be reconciled. transferred requires Stripe Transfer reversal rather than
// cancellation.
func (u *BrandFeeSettlementUsecase) Cancel(
	ctx context.Context,
	brandFeeSettlementID string,
) (*brandfeesettlementdom.BrandFeeSettlement, error) {
	if err := u.validateWriteReady(); err != nil {
		return nil, err
	}
	if brandFeeSettlementID == "" {
		return nil, brandfeesettlementdom.ErrInvalidID
	}

	current, err := u.repo.GetByID(ctx, brandFeeSettlementID)
	if err != nil {
		return nil, err
	}
	if err := current.Validate(); err != nil {
		return nil, err
	}

	switch current.Status {
	case brandfeesettlementdom.StatusPending,
		brandfeesettlementdom.StatusReady,
		brandfeesettlementdom.StatusFailedRetryable:
		nextStatus := brandfeesettlementdom.StatusCanceled
		updated, err := u.repo.UpdateByID(
			ctx,
			brandFeeSettlementID,
			brandfeesettlementdom.UpdateBrandFeeSettlementInput{
				Status: &nextStatus,
			},
		)
		if err != nil {
			return nil, err
		}
		if err := updated.Validate(); err != nil {
			return nil, err
		}

		return &updated, nil

	case brandfeesettlementdom.StatusCanceled:
		return &current, nil

	case brandfeesettlementdom.StatusTransferring,
		brandfeesettlementdom.StatusTransferred,
		brandfeesettlementdom.StatusFailed,
		brandfeesettlementdom.StatusReversed:
		return nil, ErrBrandFeeSettlementCannotCancel

	default:
		return nil, brandfeesettlementdom.ErrInvalidStatus
	}
}

// ============================================================
// Validation
// ============================================================

func validateCreatedBrandFeeSettlement(
	actual brandfeesettlementdom.BrandFeeSettlement,
	expected brandfeesettlementdom.BrandFeeSettlement,
) error {
	if err := actual.Validate(); err != nil {
		return err
	}
	if actual.Status != brandfeesettlementdom.StatusPending {
		return ErrBrandFeeSettlementExistingMismatch
	}

	return validateExistingBrandFeeSettlementAllocation(actual, expected)
}

func validateExistingBrandFeeSettlementAllocation(
	actual brandfeesettlementdom.BrandFeeSettlement,
	expected brandfeesettlementdom.BrandFeeSettlement,
) error {
	if err := actual.Validate(); err != nil {
		return err
	}
	if err := expected.Validate(); err != nil {
		return err
	}

	if actual.ID != expected.ID ||
		actual.OrderID != expected.OrderID ||
		actual.PaymentID != expected.PaymentID ||
		actual.OrderItemIndex != expected.OrderItemIndex ||
		actual.ResaleID != expected.ResaleID ||
		actual.BrandID != expected.BrandID ||
		actual.CompanyID != expected.CompanyID ||
		actual.AccountID != expected.AccountID ||
		actual.StripeAccountID != expected.StripeAccountID ||
		actual.StripePaymentIntentID != expected.StripePaymentIntentID ||
		actual.StripeChargeID != expected.StripeChargeID ||
		actual.TransferGroup != expected.TransferGroup ||
		actual.BrandFeeAmount != expected.BrandFeeAmount ||
		actual.Currency != expected.Currency {
		return ErrBrandFeeSettlementExistingMismatch
	}

	expectedID, err := brandfeesettlementdom.NewID(
		actual.PaymentID,
		actual.OrderItemIndex,
	)
	if err != nil {
		return err
	}
	if actual.ID != expectedID {
		return ErrBrandFeeSettlementExistingMismatch
	}

	return nil
}

func (u *BrandFeeSettlementUsecase) validateRepositoryReady() error {
	if u == nil || u.repo == nil {
		return ErrBrandFeeSettlementRepositoryMissing
	}

	return nil
}

func (u *BrandFeeSettlementUsecase) validateWriteReady() error {
	if err := u.validateRepositoryReady(); err != nil {
		return err
	}
	if u.now == nil {
		return ErrBrandFeeSettlementClockMissing
	}

	return nil
}
