// backend/internal/application/usecase/brand_fee_settlement_transfer.go
package usecase

import (
	"context"
	"errors"
	"fmt"
	"strings"
	"time"

	brandfeesettlementdom "narratives/internal/domain/brandFeeSettlement"
	settlementdom "narratives/internal/domain/settlement"
)

// ============================================================
// Stripe Transfer Port
// ============================================================

// StripeBrandFeeSettlementTransferGateway executes Stripe Connect Transfers for
// productBlueprint Brand fees generated by resale transactions.
//
// This port is intentionally separate from the primary-sale Settlement domain:
//
//	AMOL Stripe Platform -> productBlueprint Brand Stripe Connected Account
//
// The concrete Stripe Transfer adapter may be shared with primary Settlements
// because the underlying Stripe operation is the same Separate Charges and
// Transfers API call.
//
// CreateStripeSettlementTransferInput is reused only as the low-level transfer
// request contract. No primary-sale Settlement entity is created here.
type StripeBrandFeeSettlementTransferGateway interface {
	CreateTransfer(
		ctx context.Context,
		in CreateStripeSettlementTransferInput,
	) (*CreateStripeSettlementTransferResult, error)
}

// ============================================================
// Errors
// ============================================================

var (
	ErrBrandFeeSettlementStripeTransferGatewayMissing = errors.New("brandFeeSettlement: Stripe transfer gateway is not configured")
	ErrBrandFeeSettlementTransferNotReady             = errors.New("brandFeeSettlement: transfer is not ready")
	ErrBrandFeeSettlementStripeTransferResultEmpty    = errors.New("brandFeeSettlement: Stripe transfer result is empty")
	ErrBrandFeeSettlementStripeTransferIDEmpty        = errors.New("brandFeeSettlement: Stripe transfer id is empty")
)

// ============================================================
// Usecase
// ============================================================

const defaultBrandFeeSettlementTransferLease = 15 * time.Minute

// BrandFeeSettlementTransferUsecase executes Stripe Connect Transfers for
// productBlueprint Brand fees.
//
// It is intentionally separate from BrandFeeSettlementUsecase:
//
//   - BrandFeeSettlementUsecase manages creation, reads, ready, and cancel.
//   - BrandFeeSettlementTransferUsecase owns atomic Stripe Transfer execution.
//
// Transfer safety:
//  1. ClaimForTransfer atomically claims ready/failed_retryable/stale transferring.
//  2. Stripe is called with a deterministic Brand-fee-specific idempotency key.
//  3. CompleteTransfer persists StripeTransferID.
//  4. FailTransfer persists retryable or terminal failure state.
//
// A worker must never call Stripe after a plain GetByID without first obtaining
// an atomic transfer claim.
type BrandFeeSettlementTransferUsecase struct {
	repo BrandFeeSettlementTransferRepository

	stripeTransferGateway StripeBrandFeeSettlementTransferGateway

	transferLease time.Duration
	now           func() time.Time
}

type NewBrandFeeSettlementTransferUsecaseInput struct {
	Repository BrandFeeSettlementTransferRepository

	StripeTransferGateway StripeBrandFeeSettlementTransferGateway

	TransferLease time.Duration
	Now           func() time.Time
}

func NewBrandFeeSettlementTransferUsecase(
	in NewBrandFeeSettlementTransferUsecaseInput,
) *BrandFeeSettlementTransferUsecase {
	now := in.Now
	if now == nil {
		now = time.Now
	}

	transferLease := in.TransferLease
	if transferLease <= 0 {
		transferLease = defaultBrandFeeSettlementTransferLease
	}

	return &BrandFeeSettlementTransferUsecase{
		repo:                  in.Repository,
		stripeTransferGateway: in.StripeTransferGateway,
		transferLease:         transferLease,
		now:                   now,
	}
}

// ============================================================
// Transfer
// ============================================================

// TransferByPaymentAndOrderItem executes the Brand fee Stripe Transfer for one
// resale Order item.
//
// BrandFeeSettlement identity is deterministic:
//
//	PaymentID + "_resale_brand_fee_item_" + OrderItemIndex
func (u *BrandFeeSettlementTransferUsecase) TransferByPaymentAndOrderItem(
	ctx context.Context,
	paymentID string,
	orderItemIndex int,
) (brandfeesettlementdom.BrandFeeSettlement, error) {
	if paymentID == "" {
		return brandfeesettlementdom.BrandFeeSettlement{}, brandfeesettlementdom.ErrInvalidPaymentID
	}
	if orderItemIndex < 0 {
		return brandfeesettlementdom.BrandFeeSettlement{}, brandfeesettlementdom.ErrInvalidOrderItemIndex
	}

	brandFeeSettlementID, err := brandfeesettlementdom.NewID(paymentID, orderItemIndex)
	if err != nil {
		return brandfeesettlementdom.BrandFeeSettlement{}, err
	}

	return u.TransferByID(ctx, brandFeeSettlementID)
}

// TransferByID executes one productBlueprint Brand Stripe Connect Transfer.
//
// Execution order:
//  1. Atomically claim the BrandFeeSettlement.
//  2. Validate the immutable Brand destination.
//  3. Call Stripe using BrandFeeAmount.
//  4. Persist StripeTransferID and transferred state.
//  5. Persist failed_retryable or failed when Stripe fails.
//
// The deterministic Stripe idempotency key is namespaced separately from
// primary Settlement transfers:
//
//	brand_fee_settlement:{BrandFeeSettlementID}
func (u *BrandFeeSettlementTransferUsecase) TransferByID(
	ctx context.Context,
	brandFeeSettlementID string,
) (brandfeesettlementdom.BrandFeeSettlement, error) {
	if u == nil || u.repo == nil {
		return brandfeesettlementdom.BrandFeeSettlement{}, ErrBrandFeeSettlementRepositoryMissing
	}
	if u.stripeTransferGateway == nil {
		return brandfeesettlementdom.BrandFeeSettlement{}, ErrBrandFeeSettlementStripeTransferGatewayMissing
	}
	if u.now == nil {
		return brandfeesettlementdom.BrandFeeSettlement{}, ErrBrandFeeSettlementClockMissing
	}
	if brandFeeSettlementID == "" {
		return brandfeesettlementdom.BrandFeeSettlement{}, brandfeesettlementdom.ErrInvalidID
	}

	now := u.now().UTC()
	transferLease := u.transferLease
	if transferLease <= 0 {
		transferLease = defaultBrandFeeSettlementTransferLease
	}
	staleBefore := now.Add(-transferLease)

	brandFeeSettlement, claimed, err := u.repo.ClaimForTransfer(
		ctx,
		brandFeeSettlementID,
		now,
		staleBefore,
	)
	if err != nil {
		return brandfeesettlementdom.BrandFeeSettlement{}, err
	}

	if !claimed {
		if brandFeeSettlement.Status == brandfeesettlementdom.StatusTransferred {
			return brandFeeSettlement, nil
		}
		return brandFeeSettlement, ErrBrandFeeSettlementTransferNotReady
	}
	if brandFeeSettlement.Status != brandfeesettlementdom.StatusTransferring {
		return brandfeesettlementdom.BrandFeeSettlement{}, ErrBrandFeeSettlementTransferNotReady
	}
	if err := brandFeeSettlement.Validate(); err != nil {
		return u.failClaimedBrandFeeSettlement(ctx, brandFeeSettlement, false, nil, nil, err)
	}

	brand := brandFeeSettlement.BrandIdentity()
	if err := brand.Validate(); err != nil {
		return u.failClaimedBrandFeeSettlement(ctx, brandFeeSettlement, false, nil, nil, err)
	}
	if brandFeeSettlement.BrandFeeAmount <= 0 {
		return u.failClaimedBrandFeeSettlement(ctx, brandFeeSettlement, false, nil, nil, brandfeesettlementdom.ErrInvalidBrandFeeAmount)
	}
	if brandFeeSettlement.StripeChargeID == "" {
		return u.failClaimedBrandFeeSettlement(ctx, brandFeeSettlement, false, nil, nil, brandfeesettlementdom.ErrInvalidStripeChargeID)
	}
	if brandFeeSettlement.TransferGroup == "" {
		return u.failClaimedBrandFeeSettlement(ctx, brandFeeSettlement, false, nil, nil, brandfeesettlementdom.ErrInvalidTransferGroup)
	}
	if brandFeeSettlement.StripeAccountID != brand.StripeAccountID {
		return u.failClaimedBrandFeeSettlement(ctx, brandFeeSettlement, false, nil, nil, brandfeesettlementdom.ErrInvalidStripeAccountID)
	}

	// The existing Stripe Transfer adapter validates an Account-shaped payout
	// identity. BrandFeeSettlement stores the same immutable Company/Account/
	// StripeAccount destination captured from the Order's BrandRevenueSnapshot.
	//
	// This SellerIdentity exists only as the low-level gateway identity. It does
	// not create or imply a primary-sale Settlement record.
	gatewaySeller := settlementdom.SellerIdentity{
		Type:            settlementdom.SellerTypeAccount,
		CompanyID:       brand.CompanyID,
		AccountID:       brand.AccountID,
		StripeAccountID: brand.StripeAccountID,
	}
	if err := gatewaySeller.Validate(); err != nil {
		return u.failClaimedBrandFeeSettlement(ctx, brandFeeSettlement, false, nil, nil, err)
	}

	idempotencyKey := fmt.Sprintf(
		"brand_fee_settlement:%s",
		brandFeeSettlement.ID,
	)

	stripeResult, stripeErr := u.stripeTransferGateway.CreateTransfer(
		ctx,
		CreateStripeSettlementTransferInput{
			Amount: brandFeeSettlement.BrandFeeAmount,

			Currency: strings.ToLower(
				brandFeeSettlement.Currency,
			),

			DestinationStripeAccountID: brand.StripeAccountID,
			SourceTransaction:          brandFeeSettlement.StripeChargeID,
			TransferGroup:              brandFeeSettlement.TransferGroup,
			IdempotencyKey:             idempotencyKey,

			OrderID:      brandFeeSettlement.OrderID,
			PaymentID:    brandFeeSettlement.PaymentID,
			SettlementID: brandFeeSettlement.ID,

			Seller: gatewaySeller,
		},
	)
	if stripeErr != nil {
		return u.failClaimedBrandFeeSettlement(
			ctx,
			brandFeeSettlement,
			isSettlementTransferErrorRetryable(stripeErr),
			settlementErrorType(stripeErr),
			settlementErrorCode(stripeErr),
			stripeErr,
		)
	}
	if stripeResult == nil {
		return u.failClaimedBrandFeeSettlement(
			ctx,
			brandFeeSettlement,
			true,
			nil,
			nil,
			ErrBrandFeeSettlementStripeTransferResultEmpty,
		)
	}

	stripeTransferID := stripeResult.StripeTransferID
	if stripeTransferID == "" {
		return u.failClaimedBrandFeeSettlement(
			ctx,
			brandFeeSettlement,
			true,
			nil,
			nil,
			ErrBrandFeeSettlementStripeTransferIDEmpty,
		)
	}

	completed, err := u.repo.CompleteTransfer(
		ctx,
		brandFeeSettlement.ID,
		stripeTransferID,
		u.now().UTC(),
	)
	if err != nil {
		// Stripe may already have completed the Transfer. The same deterministic
		// idempotency key must be used by every retry so reconciliation obtains
		// the same Stripe Transfer rather than creating another one.
		return brandfeesettlementdom.BrandFeeSettlement{}, fmt.Errorf(
			"brandFeeSettlement: persist completed Stripe Transfer %q: %w",
			stripeTransferID,
			err,
		)
	}

	return completed, nil
}

// ============================================================
// Failure handling
// ============================================================

func (u *BrandFeeSettlementTransferUsecase) failClaimedBrandFeeSettlement(
	ctx context.Context,
	brandFeeSettlement brandfeesettlementdom.BrandFeeSettlement,
	retryable bool,
	errorType *string,
	errorCode *string,
	cause error,
) (brandfeesettlementdom.BrandFeeSettlement, error) {
	if cause == nil {
		cause = errors.New("brandFeeSettlement: Stripe transfer failed")
	}

	errorMessage := cause.Error()
	nextStatus := brandfeesettlementdom.StatusFailed
	if retryable {
		nextStatus = brandfeesettlementdom.StatusFailedRetryable
	}

	failed, persistErr := u.repo.FailTransfer(
		ctx,
		brandFeeSettlement.ID,
		nextStatus,
		normalizeSettlementErrorString(errorType),
		normalizeSettlementErrorString(errorCode),
		&errorMessage,
		u.now().UTC(),
	)
	if persistErr != nil {
		return brandfeesettlementdom.BrandFeeSettlement{}, fmt.Errorf(
			"brandFeeSettlement: Stripe transfer failed and failure state could not be persisted: transferErr=%v persistErr=%w",
			cause,
			persistErr,
		)
	}

	return failed, cause
}
