// backend/internal/application/usecase/resale_image_usecase.go
package usecase

import (
	"context"

	resaledom "narratives/internal/domain/resale"
)

// CreateOwnedResaleImageInput is the application input for creating
// a condition image on an owned resale.
//
// Resale ownership and audit fields are application-owned.
// CreatedAt / CreatedBy are intentionally not accepted from the caller.
type CreateOwnedResaleImageInput struct {
	ResaleID     string
	AvatarID     string
	ImageID      string
	URL          string
	DisplayOrder int
}

// CreateOwnedImage creates an image record after verifying that the
// authenticated avatar owns the target resale.
//
// Policy:
// - resale ownership is verified before mutation.
// - CreatedAt is generated by the application clock.
// - CreatedBy is always the authenticated owner AvatarID.
// - ResaleID cannot be supplied independently from the target resale.
// - low-level image validation and persistence remain in CreateImage.
func (uc *ResaleUsecase) CreateOwnedImage(
	ctx context.Context,
	input CreateOwnedResaleImageInput,
) (resaledom.ResaleImage, error) {
	if uc == nil || uc.resaleRepo == nil {
		return resaledom.ResaleImage{}, ErrNotSupported(
			"Resale.CreateOwnedImage",
		)
	}
	if input.ResaleID == "" {
		return resaledom.ResaleImage{}, resaledom.ErrInvalidConditionImageResaleID
	}
	if input.AvatarID == "" {
		return resaledom.ResaleImage{}, resaledom.ErrInvalidAvatarID
	}

	if _, err := uc.GetOwned(
		ctx,
		input.ResaleID,
		input.AvatarID,
	); err != nil {
		return resaledom.ResaleImage{}, err
	}

	return uc.CreateImage(
		ctx,
		resaledom.ResaleImage{
			ID:           input.ImageID,
			ResaleID:     input.ResaleID,
			URL:          input.URL,
			DisplayOrder: input.DisplayOrder,
			CreatedAt:    uc.nowUTC(),
			CreatedBy:    input.AvatarID,
		},
	)
}

// DeleteOwnedImage deletes an image after verifying that the authenticated
// avatar owns the target resale.
//
// The underlying DeleteImage operation retains image deletion and primary
// image cleanup responsibilities.
func (uc *ResaleUsecase) DeleteOwnedImage(
	ctx context.Context,
	resaleID string,
	imageID string,
	avatarID string,
) error {
	if uc == nil || uc.resaleRepo == nil {
		return ErrNotSupported(
			"Resale.DeleteOwnedImage",
		)
	}
	if resaleID == "" {
		return resaledom.ErrInvalidConditionImageResaleID
	}
	if avatarID == "" {
		return resaledom.ErrInvalidAvatarID
	}

	if _, err := uc.GetOwned(
		ctx,
		resaleID,
		avatarID,
	); err != nil {
		return err
	}

	return uc.DeleteImage(
		ctx,
		resaleID,
		imageID,
	)
}

// SetOwnedPrimaryImage sets the primary image after verifying that the
// authenticated avatar owns the target resale.
//
// Policy:
// - client-controlled timestamps are not accepted.
// - UpdatedAt is generated by the application clock.
// - UpdatedBy is always the authenticated owner AvatarID.
// - image existence and association validation remain in SetPrimaryImage.
func (uc *ResaleUsecase) SetOwnedPrimaryImage(
	ctx context.Context,
	resaleID string,
	imageID string,
	avatarID string,
) (resaledom.Resale, error) {
	if uc == nil || uc.resaleRepo == nil {
		return resaledom.Resale{}, ErrNotSupported(
			"Resale.SetOwnedPrimaryImage",
		)
	}
	if resaleID == "" {
		return resaledom.Resale{}, resaledom.ErrInvalidID
	}
	if avatarID == "" {
		return resaledom.Resale{}, resaledom.ErrInvalidAvatarID
	}

	if _, err := uc.GetOwned(
		ctx,
		resaleID,
		avatarID,
	); err != nil {
		return resaledom.Resale{}, err
	}

	updatedBy := avatarID

	return uc.SetPrimaryImage(
		ctx,
		resaleID,
		imageID,
		uc.nowUTC(),
		&updatedBy,
	)
}
