// backend/internal/application/usecase/return_request_usecase.go
package usecase

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"strings"
	"time"

	inquirydom "narratives/internal/domain/inquiry"
	orderdom "narratives/internal/domain/order"
)

var (
	ErrReturnRequestUsecaseNotConfigured = errors.New(
		"return request usecase: not configured",
	)
)

// ReturnRequestOrderService is the minimum Order application service required
// by ReturnRequestUsecase.
//
// Order state is authoritative for deciding whether a return is unopened or
// opened. The client-provided route or inquiryType must never bypass the Order
// domain validation.
type ReturnRequestOrderService interface {
	GetByID(
		ctx context.Context,
		id string,
	) (orderdom.Order, error)

	ReturnItem(
		ctx context.Context,
		in ReturnOrderItemInput,
	) (orderdom.Order, error)
}

// ReturnRequestInquiryCreator is the minimum Inquiry application service
// required for creating a return inquiry.
//
// Inquiry creation must go through InquiryUsecase so notification mail and
// other application-level behavior are not bypassed.
type ReturnRequestInquiryCreator interface {
	Create(
		ctx context.Context,
		inq inquirydom.Inquiry,
	) (inquirydom.Inquiry, error)
}

// ReturnRequestUsecase coordinates Order return state and its Inquiry.
//
// Responsibilities:
// - OrderDetail return -> return_unopened
// - scanned/opened return -> return_opened
// - valid scan during return_unopened -> promote to return_opened
// - prevent duplicate return inquiries for the same Order item
//
// Financial operations are intentionally outside this usecase.
// Stripe Refund / Transfer Reversal remain the responsibility of RefundUsecase.
type ReturnRequestUsecase struct {
	orderService   ReturnRequestOrderService
	inquiryRepo    inquirydom.Repository
	inquiryCreator ReturnRequestInquiryCreator

	now func() time.Time
}

func NewReturnRequestUsecase(
	orderService ReturnRequestOrderService,
	inquiryRepo inquirydom.Repository,
	inquiryCreator ReturnRequestInquiryCreator,
) *ReturnRequestUsecase {
	return &ReturnRequestUsecase{
		orderService:   orderService,
		inquiryRepo:    inquiryRepo,
		inquiryCreator: inquiryCreator,
		now:            time.Now,
	}
}

// SetNowFunc replaces the current time function for tests.
func (uc *ReturnRequestUsecase) SetNowFunc(
	now func() time.Time,
) {
	if uc == nil || now == nil {
		return
	}

	uc.now = now
}

// ReturnRequestResult is returned from all return request transitions.
//
// InquiryCreated:
// - true only when this call created a new Inquiry.
//
// InquiryPromoted:
//   - true only when this call changed
//     return_unopened -> return_opened.
type ReturnRequestResult struct {
	Order   orderdom.Order
	Inquiry inquirydom.Inquiry

	InquiryCreated  bool
	InquiryPromoted bool
}

// RequestUnopenedReturnInput identifies an unopened return request.
//
// This flow is intended for:
//
//	OrderDetail
//	-> return button
//	-> backend validates unopened state
//	-> return_unopened
//
// Inquiry subject/content are generated by the server.
type RequestUnopenedReturnInput struct {
	OrderID   string
	AvatarID  string
	ItemIndex int
}

// RequestOpenedReturnInput identifies an opened return request.
//
// This flow is intended for:
//
//	valid product scan
//	-> token transfer verified
//	-> InquiryCreatePage
//	-> backend validates opened state
//	-> return_opened
//
// ProductID is required because the scan flow has already identified the
// physical product.
type RequestOpenedReturnInput struct {
	OrderID   string
	AvatarID  string
	ItemIndex int
	ProductID string

	Subject string
	Content string
	Images  []inquirydom.ImageFile
}

// PromoteUnopenedToOpenedInput is used when a valid product scan occurs while
// an unopened return is already in progress.
//
// The token transfer itself must remain blocked. This transition only records
// that the product can no longer be treated as unopened.
type PromoteUnopenedToOpenedInput struct {
	OrderID   string
	AvatarID  string
	ItemIndex int
	ProductID string
}

const (
	defaultUnopenedReturnSubject = "返品について"

	defaultUnopenedReturnContent = "未開封商品の返品を希望します。"
	defaultOpenedReturnContent   = "開封確認済み商品の返品を希望します。"
)

// RequestUnopened records an unopened return request and creates the associated
// return_unopened Inquiry.
//
// The Order state is authoritative:
//
//	transferred == false
//	tokenTransferVerifiedAt == nil
//
// The flow is idempotent. If the Order was already updated but Inquiry creation
// failed in an earlier request, a retry creates or retrieves the missing
// Inquiry.
func (uc *ReturnRequestUsecase) RequestUnopened(
	ctx context.Context,
	in RequestUnopenedReturnInput,
) (ReturnRequestResult, error) {
	if err := uc.validateConfigured(); err != nil {
		return ReturnRequestResult{}, err
	}

	orderID := strings.TrimSpace(in.OrderID)
	if orderID == "" {
		return ReturnRequestResult{},
			orderdom.ErrInvalidID
	}

	avatarID := strings.TrimSpace(in.AvatarID)
	if avatarID == "" {
		return ReturnRequestResult{},
			orderdom.ErrInvalidAvatarID
	}

	if in.ItemIndex < 0 {
		return ReturnRequestResult{},
			orderdom.ErrInvalidItems
	}

	order, targetItem, err :=
		uc.getReturnTarget(
			ctx,
			orderID,
			avatarID,
			in.ItemIndex,
		)
	if err != nil {
		return ReturnRequestResult{}, err
	}

	if targetItem.IsCancelled ||
		!targetItem.IsDispatched ||
		targetItem.Transferred ||
		targetItem.TokenTransferVerifiedAt != nil {
		return ReturnRequestResult{},
			orderdom.ErrConflict
	}

	existing, found, err :=
		uc.findReturnInquiry(
			ctx,
			avatarID,
			orderID,
			in.ItemIndex,
		)
	if err != nil {
		return ReturnRequestResult{}, err
	}

	if found {
		switch existing.InquiryType {
		case inquirydom.InquiryTypeReturnUnopened:
			if targetItem.IsReturnRequested {
				latestOrder, latestItem, err :=
					uc.getReturnTarget(
						ctx,
						orderID,
						avatarID,
						in.ItemIndex,
					)
				if err != nil {
					return ReturnRequestResult{
						Order: order,
					}, err
				}

				return uc.reconcileReturnInquiryWithOrderState(
					ctx,
					latestOrder,
					latestItem,
					existing,
					false,
				)
			}

		case inquirydom.InquiryTypeReturnOpened:
			return ReturnRequestResult{},
				inquirydom.ErrConflict

		default:
			return ReturnRequestResult{},
				inquirydom.ErrConflict
		}
	}

	updatedOrder, err :=
		uc.orderService.ReturnItem(
			ctx,
			ReturnOrderItemInput{
				ID:        orderID,
				AvatarID:  avatarID,
				ItemIndex: in.ItemIndex,
				Kind:      orderdom.ReturnRequestKindUnopened,
			},
		)
	if err != nil {
		return ReturnRequestResult{}, err
	}

	// Re-read the Order after the return mutation.
	//
	// A verified scan may have been recorded concurrently after the initial
	// unopened-state check. The latest Order state is authoritative for the
	// Inquiry type created below.
	latestOrder, latestItem, err :=
		uc.getReturnTarget(
			ctx,
			orderID,
			avatarID,
			in.ItemIndex,
		)
	if err != nil {
		return ReturnRequestResult{
			Order: updatedOrder,
		}, err
	}

	updatedOrder = latestOrder

	if latestItem.IsCancelled ||
		!latestItem.IsDispatched ||
		!latestItem.IsReturnRequested {
		return ReturnRequestResult{
			Order: updatedOrder,
		}, orderdom.ErrConflict
	}

	// Check again after the Order mutation.
	//
	// This recovers from:
	// - a previous Order update followed by Inquiry creation failure
	// - another request creating the Inquiry concurrently
	// - a verified scan promoting the return concurrently
	existing, found, err =
		uc.findReturnInquiry(
			ctx,
			avatarID,
			orderID,
			in.ItemIndex,
		)
	if err != nil {
		return ReturnRequestResult{
			Order: updatedOrder,
		}, err
	}

	if found {
		return uc.reconcileReturnInquiryWithOrderState(
			ctx,
			updatedOrder,
			latestItem,
			existing,
			false,
		)
	}

	now := uc.nowUTC()

	var inquiry inquirydom.Inquiry

	opened :=
		latestItem.Transferred ||
			latestItem.TokenTransferVerifiedAt != nil

	if opened {
		inquiry, err =
			inquirydom.NewReturnOpened(
				returnInquiryID(
					orderID,
					in.ItemIndex,
				),
				latestItem.ProductID,
				orderID,
				in.ItemIndex,
				avatarID,
				defaultUnopenedReturnSubject,
				defaultOpenedReturnContent,
				now,
				now,
			)
	} else {
		inquiry, err =
			inquirydom.NewReturnUnopened(
				returnInquiryID(
					orderID,
					in.ItemIndex,
				),
				latestItem.ProductID,
				orderID,
				in.ItemIndex,
				avatarID,
				defaultUnopenedReturnSubject,
				defaultUnopenedReturnContent,
				now,
				now,
			)
	}
	if err != nil {
		return ReturnRequestResult{
			Order: updatedOrder,
		}, err
	}

	inquiry.Images =
		[]inquirydom.ImageFile{}

	created, err :=
		uc.inquiryCreator.Create(
			ctx,
			inquiry,
		)
	if err != nil {
		// A deterministic Inquiry ID prevents concurrent requests from creating
		// duplicate return inquiries. If another request won the create race,
		// retrieve that Inquiry and reconcile it against the latest Order state.
		if errors.Is(
			err,
			inquirydom.ErrConflict,
		) {
			latestOrder, latestItem, latestErr :=
				uc.getReturnTarget(
					ctx,
					orderID,
					avatarID,
					in.ItemIndex,
				)
			if latestErr != nil {
				return ReturnRequestResult{
					Order: updatedOrder,
				}, latestErr
			}

			existing, found, findErr :=
				uc.findReturnInquiry(
					ctx,
					avatarID,
					orderID,
					in.ItemIndex,
				)
			if findErr != nil {
				return ReturnRequestResult{
					Order: latestOrder,
				}, findErr
			}

			if found {
				return uc.reconcileReturnInquiryWithOrderState(
					ctx,
					latestOrder,
					latestItem,
					existing,
					false,
				)
			}
		}

		return ReturnRequestResult{
			Order:          updatedOrder,
			Inquiry:        created,
			InquiryCreated: created.ID != "",
		}, err
	}

	// Re-read once more after Inquiry creation.
	//
	// This closes the remaining race where the verified scan is persisted after
	// the pre-create Order read but before the Inquiry create completes.
	latestOrder, latestItem, err =
		uc.getReturnTarget(
			ctx,
			orderID,
			avatarID,
			in.ItemIndex,
		)
	if err != nil {
		return ReturnRequestResult{
			Order:          updatedOrder,
			Inquiry:        created,
			InquiryCreated: true,
		}, err
	}

	return uc.reconcileReturnInquiryWithOrderState(
		ctx,
		latestOrder,
		latestItem,
		created,
		true,
	)
}

// RequestOpened records an opened return request and creates or updates the
// associated return Inquiry.
//
// The Order state is authoritative:
//
//	transferred == true
//
// OR:
//
//	tokenTransferVerifiedAt != nil
//
// Therefore a client cannot forge return_opened only by sending that
// inquiryType.
func (uc *ReturnRequestUsecase) RequestOpened(
	ctx context.Context,
	in RequestOpenedReturnInput,
) (ReturnRequestResult, error) {
	if err := uc.validateConfigured(); err != nil {
		return ReturnRequestResult{}, err
	}

	orderID := strings.TrimSpace(in.OrderID)
	if orderID == "" {
		return ReturnRequestResult{},
			orderdom.ErrInvalidID
	}

	avatarID := strings.TrimSpace(in.AvatarID)
	if avatarID == "" {
		return ReturnRequestResult{},
			orderdom.ErrInvalidAvatarID
	}

	productID := strings.TrimSpace(in.ProductID)
	if productID == "" {
		return ReturnRequestResult{},
			inquirydom.ErrInvalidProductID
	}

	if in.ItemIndex < 0 {
		return ReturnRequestResult{},
			orderdom.ErrInvalidItems
	}

	_, targetItem, err :=
		uc.getReturnTarget(
			ctx,
			orderID,
			avatarID,
			in.ItemIndex,
		)
	if err != nil {
		return ReturnRequestResult{}, err
	}

	if targetItem.IsCancelled ||
		!targetItem.IsDispatched {
		return ReturnRequestResult{},
			orderdom.ErrConflict
	}

	if !targetItem.Transferred &&
		targetItem.TokenTransferVerifiedAt == nil {
		return ReturnRequestResult{},
			orderdom.ErrConflict
	}

	if targetItem.ProductID != "" &&
		targetItem.ProductID != productID {
		return ReturnRequestResult{},
			orderdom.ErrNotFound
	}

	updatedOrder, err :=
		uc.orderService.ReturnItem(
			ctx,
			ReturnOrderItemInput{
				ID:        orderID,
				AvatarID:  avatarID,
				ItemIndex: in.ItemIndex,
				Kind:      orderdom.ReturnRequestKindOpened,
			},
		)
	if err != nil {
		return ReturnRequestResult{}, err
	}

	existing, found, err :=
		uc.findReturnInquiry(
			ctx,
			avatarID,
			orderID,
			in.ItemIndex,
		)
	if err != nil {
		return ReturnRequestResult{
			Order: updatedOrder,
		}, err
	}

	if found {
		switch existing.InquiryType {
		case inquirydom.InquiryTypeReturnOpened:
			if err := validateReturnInquiryProductID(
				existing,
				productID,
			); err != nil {
				return ReturnRequestResult{
					Order: updatedOrder,
				}, err
			}

			if existing.ProductID == "" {
				updatedInquiry, err :=
					uc.setReturnInquiryProductID(
						ctx,
						existing,
						productID,
					)
				if err != nil {
					return ReturnRequestResult{
						Order: updatedOrder,
					}, err
				}

				existing = updatedInquiry
			}

			return ReturnRequestResult{
				Order:   updatedOrder,
				Inquiry: existing,
			}, nil

		case inquirydom.InquiryTypeReturnUnopened:
			promoted, err :=
				uc.promoteInquiryToOpened(
					ctx,
					existing,
					productID,
				)
			if err != nil {
				return ReturnRequestResult{
					Order: updatedOrder,
				}, err
			}

			return ReturnRequestResult{
				Order:           updatedOrder,
				Inquiry:         promoted,
				InquiryPromoted: true,
			}, nil

		default:
			return ReturnRequestResult{
				Order: updatedOrder,
			}, inquirydom.ErrConflict
		}
	}

	now := uc.nowUTC()

	inquiry := inquirydom.Inquiry{
		ID: returnInquiryID(
			orderID,
			in.ItemIndex,
		),
		ProductID: productID,
		OrderID:   orderID,
		OrderItemIndex: intPointer(
			in.ItemIndex,
		),
		AvatarID:    avatarID,
		Subject:     in.Subject,
		Content:     in.Content,
		Status:      inquirydom.InquiryStatusOpen,
		InquiryType: inquirydom.InquiryTypeReturnOpened,
		IsRead:      false,
		Images:      in.Images,
		CreatedAt:   now,
		UpdatedAt:   now,
	}

	created, err :=
		uc.inquiryCreator.Create(
			ctx,
			inquiry,
		)
	if err != nil {
		if errors.Is(
			err,
			inquirydom.ErrConflict,
		) {
			existing, found, findErr :=
				uc.findReturnInquiry(
					ctx,
					avatarID,
					orderID,
					in.ItemIndex,
				)
			if findErr != nil {
				return ReturnRequestResult{
					Order: updatedOrder,
				}, findErr
			}

			if found {
				switch existing.InquiryType {
				case inquirydom.InquiryTypeReturnOpened:
					if err := validateReturnInquiryProductID(
						existing,
						productID,
					); err != nil {
						return ReturnRequestResult{
							Order: updatedOrder,
						}, err
					}

					return ReturnRequestResult{
						Order:   updatedOrder,
						Inquiry: existing,
					}, nil

				case inquirydom.InquiryTypeReturnUnopened:
					promoted, promoteErr :=
						uc.promoteInquiryToOpened(
							ctx,
							existing,
							productID,
						)
					if promoteErr != nil {
						return ReturnRequestResult{
							Order: updatedOrder,
						}, promoteErr
					}

					return ReturnRequestResult{
						Order:           updatedOrder,
						Inquiry:         promoted,
						InquiryPromoted: true,
					}, nil
				}
			}
		}

		return ReturnRequestResult{
			Order:          updatedOrder,
			Inquiry:        created,
			InquiryCreated: created.ID != "",
		}, err
	}

	return ReturnRequestResult{
		Order:          updatedOrder,
		Inquiry:        created,
		InquiryCreated: true,
	}, nil
}

// PromoteUnopenedToOpened changes an existing return_unopened Inquiry to
// return_opened after a valid product scan.
//
// This method does not transfer the token.
//
// Expected flow:
//
//	return_unopened
//	-> valid scan
//	-> tokenTransferVerifiedAt recorded
//	-> PromoteUnopenedToOpened
//	-> token transfer blocked
func (uc *ReturnRequestUsecase) PromoteUnopenedToOpened(
	ctx context.Context,
	in PromoteUnopenedToOpenedInput,
) (ReturnRequestResult, error) {
	if err := uc.validateConfigured(); err != nil {
		return ReturnRequestResult{}, err
	}

	orderID := strings.TrimSpace(in.OrderID)
	if orderID == "" {
		return ReturnRequestResult{},
			orderdom.ErrInvalidID
	}

	avatarID := strings.TrimSpace(in.AvatarID)
	if avatarID == "" {
		return ReturnRequestResult{},
			orderdom.ErrInvalidAvatarID
	}

	productID := strings.TrimSpace(in.ProductID)
	if productID == "" {
		return ReturnRequestResult{},
			inquirydom.ErrInvalidProductID
	}

	if in.ItemIndex < 0 {
		return ReturnRequestResult{},
			orderdom.ErrInvalidItems
	}

	order, targetItem, err :=
		uc.getReturnTarget(
			ctx,
			orderID,
			avatarID,
			in.ItemIndex,
		)
	if err != nil {
		return ReturnRequestResult{}, err
	}

	if targetItem.IsCancelled ||
		!targetItem.IsDispatched ||
		!targetItem.IsReturnRequested {
		return ReturnRequestResult{},
			orderdom.ErrConflict
	}

	if !targetItem.Transferred &&
		targetItem.TokenTransferVerifiedAt == nil {
		return ReturnRequestResult{},
			orderdom.ErrConflict
	}

	if targetItem.ProductID != "" &&
		targetItem.ProductID != productID {
		return ReturnRequestResult{},
			orderdom.ErrNotFound
	}

	existing, found, err :=
		uc.findReturnInquiry(
			ctx,
			avatarID,
			orderID,
			in.ItemIndex,
		)
	if err != nil {
		return ReturnRequestResult{
			Order: order,
		}, err
	}

	if !found {
		return ReturnRequestResult{
			Order: order,
		}, inquirydom.ErrNotFound
	}

	switch existing.InquiryType {
	case inquirydom.InquiryTypeReturnOpened:
		if err := validateReturnInquiryProductID(
			existing,
			productID,
		); err != nil {
			return ReturnRequestResult{
				Order: order,
			}, err
		}

		if existing.ProductID == "" {
			updatedInquiry, err :=
				uc.setReturnInquiryProductID(
					ctx,
					existing,
					productID,
				)
			if err != nil {
				return ReturnRequestResult{
					Order: order,
				}, err
			}

			existing = updatedInquiry
		}

		return ReturnRequestResult{
			Order:   order,
			Inquiry: existing,
		}, nil

	case inquirydom.InquiryTypeReturnUnopened:
		promoted, err :=
			uc.promoteInquiryToOpened(
				ctx,
				existing,
				productID,
			)
		if err != nil {
			return ReturnRequestResult{
				Order: order,
			}, err
		}

		return ReturnRequestResult{
			Order:           order,
			Inquiry:         promoted,
			InquiryPromoted: true,
		}, nil

	default:
		return ReturnRequestResult{
			Order: order,
		}, inquirydom.ErrConflict
	}
}

func (uc *ReturnRequestUsecase) getReturnTarget(
	ctx context.Context,
	orderID string,
	avatarID string,
	itemIndex int,
) (
	orderdom.Order,
	orderdom.OrderItemSnapshot,
	error,
) {
	order, err :=
		uc.orderService.GetByID(
			ctx,
			orderID,
		)
	if err != nil {
		return orderdom.Order{},
			orderdom.OrderItemSnapshot{},
			err
	}

	if order.AvatarID != avatarID {
		return orderdom.Order{},
			orderdom.OrderItemSnapshot{},
			orderdom.ErrNotFound
	}

	if itemIndex < 0 ||
		itemIndex >= len(order.Items) {
		return orderdom.Order{},
			orderdom.OrderItemSnapshot{},
			orderdom.ErrNotFound
	}

	return order,
		order.Items[itemIndex],
		nil
}

func (uc *ReturnRequestUsecase) findReturnInquiry(
	ctx context.Context,
	avatarID string,
	orderID string,
	itemIndex int,
) (
	inquirydom.Inquiry,
	bool,
	error,
) {
	notDeleted := false

	result, err :=
		uc.inquiryRepo.ListByAvatarID(
			ctx,
			avatarID,
			inquirydom.Filter{
				OrderID:        &orderID,
				OrderItemIndex: &itemIndex,
				Deleted:        &notDeleted,
			},
			inquirydom.Sort{},
			inquirydom.Page{
				Number:  1,
				PerPage: 200,
			},
		)
	if err != nil {
		return inquirydom.Inquiry{},
			false,
			err
	}

	var found *inquirydom.Inquiry

	for index := range result.Items {
		inquiry := result.Items[index]

		switch inquiry.InquiryType {
		case inquirydom.InquiryTypeReturnUnopened,
			inquirydom.InquiryTypeReturnOpened:
		default:
			continue
		}

		if found != nil {
			// More than one active return inquiry for the same Order item means
			// the persisted state has violated the one-return-inquiry invariant.
			return inquirydom.Inquiry{},
				false,
				inquirydom.ErrConflict
		}

		copy := inquiry
		found = &copy
	}

	if found == nil {
		return inquirydom.Inquiry{},
			false,
			nil
	}

	return *found,
		true,
		nil
}

func (uc *ReturnRequestUsecase) reconcileReturnInquiryWithOrderState(
	ctx context.Context,
	order orderdom.Order,
	item orderdom.OrderItemSnapshot,
	inquiry inquirydom.Inquiry,
	created bool,
) (ReturnRequestResult, error) {
	if item.IsCancelled ||
		!item.IsDispatched ||
		!item.IsReturnRequested {
		return ReturnRequestResult{
			Order:          order,
			Inquiry:        inquiry,
			InquiryCreated: created,
		}, orderdom.ErrConflict
	}

	opened :=
		item.Transferred ||
			item.TokenTransferVerifiedAt != nil

	if !opened {
		if inquiry.InquiryType !=
			inquirydom.InquiryTypeReturnUnopened {
			return ReturnRequestResult{
				Order:          order,
				Inquiry:        inquiry,
				InquiryCreated: created,
			}, inquirydom.ErrConflict
		}

		return ReturnRequestResult{
			Order:          order,
			Inquiry:        inquiry,
			InquiryCreated: created,
		}, nil
	}

	switch inquiry.InquiryType {
	case inquirydom.InquiryTypeReturnOpened:
		if item.ProductID != "" {
			if err := validateReturnInquiryProductID(
				inquiry,
				item.ProductID,
			); err != nil {
				return ReturnRequestResult{
					Order:          order,
					Inquiry:        inquiry,
					InquiryCreated: created,
				}, err
			}

			if inquiry.ProductID == "" {
				updatedInquiry, err :=
					uc.setReturnInquiryProductID(
						ctx,
						inquiry,
						item.ProductID,
					)
				if err != nil {
					return ReturnRequestResult{
						Order:          order,
						Inquiry:        inquiry,
						InquiryCreated: created,
					}, err
				}

				inquiry = updatedInquiry
			}
		}

		return ReturnRequestResult{
			Order:          order,
			Inquiry:        inquiry,
			InquiryCreated: created,
		}, nil

	case inquirydom.InquiryTypeReturnUnopened:
		promoted, err :=
			uc.promoteInquiryToOpened(
				ctx,
				inquiry,
				item.ProductID,
			)
		if err != nil {
			return ReturnRequestResult{
				Order:          order,
				Inquiry:        inquiry,
				InquiryCreated: created,
			}, err
		}

		return ReturnRequestResult{
			Order:           order,
			Inquiry:         promoted,
			InquiryCreated:  created,
			InquiryPromoted: true,
		}, nil

	default:
		return ReturnRequestResult{
			Order:          order,
			Inquiry:        inquiry,
			InquiryCreated: created,
		}, inquirydom.ErrConflict
	}
}

func (uc *ReturnRequestUsecase) promoteInquiryToOpened(
	ctx context.Context,
	inquiry inquirydom.Inquiry,
	productID string,
) (inquirydom.Inquiry, error) {
	productID = strings.TrimSpace(productID)

	if productID != "" {
		if err := validateReturnInquiryProductID(
			inquiry,
			productID,
		); err != nil {
			return inquirydom.Inquiry{}, err
		}
	}

	now := uc.nowUTC()

	if err := inquiry.PromoteReturnOpened(
		now,
	); err != nil {
		return inquirydom.Inquiry{}, err
	}

	inquiryType :=
		inquirydom.InquiryTypeReturnOpened

	patch := inquirydom.InquiryPatch{
		InquiryType: &inquiryType,
		UpdatedAt:   &now,
	}

	if inquiry.ProductID == "" &&
		productID != "" {
		patch.ProductID = &productID
	}

	return uc.inquiryRepo.Update(
		ctx,
		inquiry.ID,
		patch,
	)
}

func (uc *ReturnRequestUsecase) setReturnInquiryProductID(
	ctx context.Context,
	inquiry inquirydom.Inquiry,
	productID string,
) (inquirydom.Inquiry, error) {
	if inquiry.ProductID != "" {
		if inquiry.ProductID != productID {
			return inquirydom.Inquiry{},
				inquirydom.ErrConflict
		}

		return inquiry, nil
	}

	now := uc.nowUTC()

	return uc.inquiryRepo.Update(
		ctx,
		inquiry.ID,
		inquirydom.InquiryPatch{
			ProductID: &productID,
			UpdatedAt: &now,
		},
	)
}

func validateReturnInquiryProductID(
	inquiry inquirydom.Inquiry,
	productID string,
) error {
	productID = strings.TrimSpace(productID)
	if productID == "" {
		return inquirydom.ErrInvalidProductID
	}

	if inquiry.ProductID != "" &&
		inquiry.ProductID != productID {
		return inquirydom.ErrConflict
	}

	return nil
}

func (uc *ReturnRequestUsecase) validateConfigured() error {
	if uc == nil ||
		uc.orderService == nil ||
		uc.inquiryRepo == nil ||
		uc.inquiryCreator == nil {
		return ErrReturnRequestUsecaseNotConfigured
	}

	return nil
}

func (uc *ReturnRequestUsecase) nowUTC() time.Time {
	if uc == nil || uc.now == nil {
		return time.Now().UTC()
	}

	return uc.now().UTC()
}

// returnInquiryID generates one stable Inquiry ID per Order item.
//
// A deterministic ID prevents two concurrent requests from creating separate
// return inquiries for the same Order item.
func returnInquiryID(
	orderID string,
	itemIndex int,
) string {
	source := fmt.Sprintf(
		"%s:%d",
		orderID,
		itemIndex,
	)

	sum := sha256.Sum256(
		[]byte(source),
	)

	return "inq_return_" +
		hex.EncodeToString(
			sum[:16],
		)
}

func intPointer(value int) *int {
	v := value
	return &v
}
