// backend/internal/domain/brandFeeSettlement/entity.go
package brandFeeSettlement

import (
	"errors"
	"strconv"
	"strings"
	"time"
)

// Status represents the Stripe Connect transfer lifecycle for the
// productBlueprint Brand share generated by one resale Order item.
//
// pending:
//   - buyer payment has succeeded
//   - the Brand fee record exists
//   - the resale fulfillment boundary has not yet made the transfer executable
//
// ready:
//   - the Brand fee may be transferred to the snapshotted Brand Stripe Account
//
// transferring:
//   - a worker has claimed the record and is executing the Stripe Transfer
//
// transferred:
//   - the Stripe Transfer has completed
//
// failed_retryable:
//   - the Stripe Transfer failed but may be retried
//
// failed:
//   - the Stripe Transfer failed permanently
//
// canceled:
//   - the Brand fee was canceled before transfer
//
// reversed:
//   - the completed Stripe Transfer was fully reversed
type Status string

const (
	StatusPending         Status = "pending"
	StatusReady           Status = "ready"
	StatusTransferring    Status = "transferring"
	StatusTransferred     Status = "transferred"
	StatusFailedRetryable Status = "failed_retryable"
	StatusFailed          Status = "failed"
	StatusCanceled        Status = "canceled"
	StatusReversed        Status = "reversed"
)

var AllowedStatuses = map[Status]struct{}{
	StatusPending:         {},
	StatusReady:           {},
	StatusTransferring:    {},
	StatusTransferred:     {},
	StatusFailedRetryable: {},
	StatusFailed:          {},
	StatusCanceled:        {},
	StatusReversed:        {},
}

const CurrencyJPY = "JPY"

var DefaultStatus = StatusPending

var (
	ErrInvalidID                       = errors.New("brandFeeSettlement: invalid id")
	ErrInvalidOrderID                  = errors.New("brandFeeSettlement: invalid orderId")
	ErrInvalidPaymentID                = errors.New("brandFeeSettlement: invalid paymentId")
	ErrPaymentOrderMismatch            = errors.New("brandFeeSettlement: paymentId does not match orderId")
	ErrInvalidOrderItemIndex           = errors.New("brandFeeSettlement: invalid orderItemIndex")
	ErrInvalidResaleID                 = errors.New("brandFeeSettlement: invalid resaleId")
	ErrInvalidBrandID                  = errors.New("brandFeeSettlement: invalid brandId")
	ErrInvalidCompanyID                = errors.New("brandFeeSettlement: invalid companyId")
	ErrInvalidAccountID                = errors.New("brandFeeSettlement: invalid accountId")
	ErrInvalidStripeAccountID          = errors.New("brandFeeSettlement: invalid stripeAccountId")
	ErrInvalidStripePaymentIntentID    = errors.New("brandFeeSettlement: invalid stripePaymentIntentId")
	ErrInvalidStripeChargeID           = errors.New("brandFeeSettlement: invalid stripeChargeId")
	ErrInvalidStripeTransferID         = errors.New("brandFeeSettlement: invalid stripeTransferId")
	ErrInvalidStripeTransferReversalID = errors.New("brandFeeSettlement: invalid stripeTransferReversalId")
	ErrInvalidTransferGroup            = errors.New("brandFeeSettlement: invalid transferGroup")
	ErrInvalidBrandFeeAmount           = errors.New("brandFeeSettlement: invalid brandFeeAmount")
	ErrInvalidCurrency                 = errors.New("brandFeeSettlement: invalid currency")
	ErrInvalidStatus                   = errors.New("brandFeeSettlement: invalid status")
	ErrInvalidStatusTransition         = errors.New("brandFeeSettlement: invalid status transition")
	ErrInvalidErrorType                = errors.New("brandFeeSettlement: invalid errorType")
	ErrInvalidErrorCode                = errors.New("brandFeeSettlement: invalid errorCode")
	ErrInvalidErrorMsg                 = errors.New("brandFeeSettlement: invalid errorMsg")
	ErrFailureReasonRequired           = errors.New("brandFeeSettlement: failure reason is required")
	ErrInvalidCreatedAt                = errors.New("brandFeeSettlement: invalid createdAt")
	ErrInvalidUpdatedAt                = errors.New("brandFeeSettlement: invalid updatedAt")
	ErrInvalidTransferredAt            = errors.New("brandFeeSettlement: invalid transferredAt")
	ErrInvalidReversedAt               = errors.New("brandFeeSettlement: invalid reversedAt")
)

// BrandIdentity is the immutable productBlueprint Brand payout destination
// captured in the Order item at Order creation.
//
// The destination must never be re-resolved from the current Brand or Account
// when a Stripe Transfer is executed.
type BrandIdentity struct {
	BrandID         string `json:"brandId" firestore:"brandId"`
	CompanyID       string `json:"companyId" firestore:"companyId"`
	AccountID       string `json:"accountId" firestore:"accountId"`
	StripeAccountID string `json:"stripeAccountId" firestore:"stripeAccountId"`
}

func (b BrandIdentity) Validate() error {
	if b.BrandID == "" {
		return ErrInvalidBrandID
	}
	if b.CompanyID == "" {
		return ErrInvalidCompanyID
	}
	if b.AccountID == "" {
		return ErrInvalidAccountID
	}
	if !isStripeAccountID(b.StripeAccountID) {
		return ErrInvalidStripeAccountID
	}
	return nil
}

// BrandFeeSettlement represents the productBlueprint Brand's share generated by
// exactly one successfully paid resale Order item.
//
// One active resale Order item creates at most one BrandFeeSettlement.
//
// Brand fees are intentionally not aggregated by AccountID. This preserves the
// exact source Order item and prevents collisions with primary-sale Settlement
// records or other resale items belonging to the same Brand.
//
// BrandFeeAmount is calculated by the settlement calculator before this entity
// is created. This domain does not recalculate the percentage.
//
// Current resale allocation:
//
//	MerchandiseAmount - ShippingAmount = resale distribution base
//	BrandFeeAmount = 5% of that distribution base
//
// The corresponding SalesReceivable separately stores the complete resale
// allocation. BrandFeeSettlement represents only the Brand Stripe Transfer.
//
// StripeTransferID is the Stripe Connect Transfer ID and is unrelated to the
// Solana token ownership transfer.
type BrandFeeSettlement struct {
	ID string `json:"id" firestore:"id"`

	OrderID        string `json:"orderId" firestore:"orderId"`
	PaymentID      string `json:"paymentId" firestore:"paymentId"`
	OrderItemIndex int    `json:"orderItemIndex" firestore:"orderItemIndex"`
	ResaleID       string `json:"resaleId" firestore:"resaleId"`

	BrandID         string `json:"brandId" firestore:"brandId"`
	CompanyID       string `json:"companyId" firestore:"companyId"`
	AccountID       string `json:"accountId" firestore:"accountId"`
	StripeAccountID string `json:"stripeAccountId" firestore:"stripeAccountId"`

	StripePaymentIntentID string `json:"stripePaymentIntentId" firestore:"stripePaymentIntentId"`
	StripeChargeID        string `json:"stripeChargeId" firestore:"stripeChargeId"`
	StripeTransferID      string `json:"stripeTransferId,omitempty" firestore:"stripeTransferId,omitempty"`

	StripeTransferReversalID string `json:"stripeTransferReversalId,omitempty" firestore:"stripeTransferReversalId,omitempty"`

	TransferGroup string `json:"transferGroup" firestore:"transferGroup"`

	BrandFeeAmount int `json:"brandFeeAmount" firestore:"brandFeeAmount"`

	Currency string `json:"currency" firestore:"currency"`
	Status   Status `json:"status" firestore:"status"`

	ErrorType *string `json:"errorType,omitempty" firestore:"errorType,omitempty"`
	ErrorCode *string `json:"errorCode,omitempty" firestore:"errorCode,omitempty"`
	ErrorMsg  *string `json:"errorMsg,omitempty" firestore:"errorMsg,omitempty"`

	CreatedAt time.Time `json:"createdAt" firestore:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt" firestore:"updatedAt"`

	TransferredAt *time.Time `json:"transferredAt,omitempty" firestore:"transferredAt,omitempty"`
	ReversedAt    *time.Time `json:"reversedAt,omitempty" firestore:"reversedAt,omitempty"`
}

// NewID creates the deterministic Firestore document ID.
//
//	paymentID + "_resale_brand_fee_item_" + orderItemIndex
//
// OrderItemIndex is included because one Payment may contain multiple resale
// items belonging to the same Brand or Account. Each item must retain an
// independent transfer and refund/reversal lifecycle.
func NewID(paymentID string, orderItemIndex int) (string, error) {
	if paymentID == "" {
		return "", ErrInvalidPaymentID
	}
	if strings.Contains(paymentID, "/") {
		return "", ErrInvalidID
	}
	if orderItemIndex < 0 {
		return "", ErrInvalidOrderItemIndex
	}

	return paymentID + "_resale_brand_fee_item_" + strconv.Itoa(orderItemIndex), nil
}

func IsValidStatus(status Status) bool {
	if status == "" {
		return false
	}

	_, ok := AllowedStatuses[status]
	return ok
}

// New creates a pending BrandFeeSettlement after successful buyer payment.
//
// stripePaymentIntentID and stripeChargeID must already be known.
// StripeTransferID and StripeTransferReversalID are intentionally empty.
//
// Payment success only creates the pending record. The application layer must
// explicitly move it to ready after the required resale fulfillment boundary.
func New(
	id string,
	orderID string,
	paymentID string,
	orderItemIndex int,
	resaleID string,
	brand BrandIdentity,
	stripePaymentIntentID string,
	stripeChargeID string,
	transferGroup string,
	brandFeeAmount int,
	currency string,
	createdAt time.Time,
) (BrandFeeSettlement, error) {
	if err := brand.Validate(); err != nil {
		return BrandFeeSettlement{}, err
	}

	createdAt = createdAt.UTC()

	settlement := BrandFeeSettlement{
		ID: id,

		OrderID:        orderID,
		PaymentID:      paymentID,
		OrderItemIndex: orderItemIndex,
		ResaleID:       resaleID,

		BrandID:         brand.BrandID,
		CompanyID:       brand.CompanyID,
		AccountID:       brand.AccountID,
		StripeAccountID: brand.StripeAccountID,

		StripePaymentIntentID:    stripePaymentIntentID,
		StripeChargeID:           stripeChargeID,
		StripeTransferID:         "",
		StripeTransferReversalID: "",

		TransferGroup: transferGroup,

		BrandFeeAmount: brandFeeAmount,

		Currency: currency,
		Status:   DefaultStatus,

		ErrorType: nil,
		ErrorCode: nil,
		ErrorMsg:  nil,

		CreatedAt: createdAt,
		UpdatedAt: createdAt,

		TransferredAt: nil,
		ReversedAt:    nil,
	}

	if err := settlement.Validate(); err != nil {
		return BrandFeeSettlement{}, err
	}

	return settlement, nil
}

// BrandIdentity returns the immutable Brand payout destination stored by this
// BrandFeeSettlement.
func (s BrandFeeSettlement) BrandIdentity() BrandIdentity {
	return BrandIdentity{
		BrandID:         s.BrandID,
		CompanyID:       s.CompanyID,
		AccountID:       s.AccountID,
		StripeAccountID: s.StripeAccountID,
	}
}

// MarkReady makes the Brand fee eligible for Stripe Transfer.
//
// Only pending may become ready.
func (s *BrandFeeSettlement) MarkReady(now time.Time) error {
	if s == nil || s.Status != StatusPending {
		return ErrInvalidStatusTransition
	}
	if now.IsZero() {
		return ErrInvalidUpdatedAt
	}

	s.Status = StatusReady
	s.ErrorType = nil
	s.ErrorCode = nil
	s.ErrorMsg = nil
	s.UpdatedAt = now.UTC()

	return s.Validate()
}

// StartTransfer claims the Brand fee for Stripe Transfer processing.
func (s *BrandFeeSettlement) StartTransfer(now time.Time) error {
	if s == nil {
		return ErrInvalidStatusTransition
	}

	switch s.Status {
	case StatusReady, StatusFailedRetryable:
	default:
		return ErrInvalidStatusTransition
	}

	if now.IsZero() {
		return ErrInvalidUpdatedAt
	}

	s.Status = StatusTransferring
	s.ErrorType = nil
	s.ErrorCode = nil
	s.ErrorMsg = nil
	s.UpdatedAt = now.UTC()

	return s.Validate()
}

// ReclaimTransfer refreshes a stale transferring claim.
//
// The application/repository layer is responsible for deciding whether the
// existing claim is stale.
func (s *BrandFeeSettlement) ReclaimTransfer(now time.Time) error {
	if s == nil || s.Status != StatusTransferring {
		return ErrInvalidStatusTransition
	}
	if now.IsZero() {
		return ErrInvalidUpdatedAt
	}

	now = now.UTC()
	if !now.After(s.UpdatedAt) {
		return ErrInvalidUpdatedAt
	}

	s.ErrorType = nil
	s.ErrorCode = nil
	s.ErrorMsg = nil
	s.UpdatedAt = now

	return s.Validate()
}

// MarkTransferred records a successful Stripe Connect Transfer.
func (s *BrandFeeSettlement) MarkTransferred(
	stripeTransferID string,
	now time.Time,
) error {
	if s == nil || s.Status != StatusTransferring {
		return ErrInvalidStatusTransition
	}
	if !isStripeTransferID(stripeTransferID) {
		return ErrInvalidStripeTransferID
	}
	if now.IsZero() {
		return ErrInvalidTransferredAt
	}

	transferredAt := now.UTC()

	s.StripeTransferID = stripeTransferID
	s.Status = StatusTransferred
	s.ErrorType = nil
	s.ErrorCode = nil
	s.ErrorMsg = nil
	s.TransferredAt = &transferredAt
	s.UpdatedAt = transferredAt

	return s.Validate()
}

// MarkFailedRetryable records a Stripe Transfer failure that may be retried.
func (s *BrandFeeSettlement) MarkFailedRetryable(
	errorType *string,
	errorCode *string,
	errorMsg *string,
	now time.Time,
) error {
	if s == nil || s.Status != StatusTransferring {
		return ErrInvalidStatusTransition
	}
	if err := validateFailureReason(errorType, errorCode, errorMsg); err != nil {
		return err
	}
	if now.IsZero() {
		return ErrInvalidUpdatedAt
	}

	s.Status = StatusFailedRetryable
	s.ErrorType = errorType
	s.ErrorCode = errorCode
	s.ErrorMsg = errorMsg
	s.UpdatedAt = now.UTC()

	return s.Validate()
}

// MarkFailed records a terminal Stripe Transfer failure.
func (s *BrandFeeSettlement) MarkFailed(
	errorType *string,
	errorCode *string,
	errorMsg *string,
	now time.Time,
) error {
	if s == nil || s.Status != StatusTransferring {
		return ErrInvalidStatusTransition
	}
	if err := validateFailureReason(errorType, errorCode, errorMsg); err != nil {
		return err
	}
	if now.IsZero() {
		return ErrInvalidUpdatedAt
	}

	s.Status = StatusFailed
	s.ErrorType = errorType
	s.ErrorCode = errorCode
	s.ErrorMsg = errorMsg
	s.UpdatedAt = now.UTC()

	return s.Validate()
}

// Cancel cancels a Brand fee that has not been transferred.
//
// A transferring record cannot be canceled because the Stripe request result
// must first be reconciled. A transferred record must be reversed instead.
func (s *BrandFeeSettlement) Cancel(now time.Time) error {
	if s == nil {
		return ErrInvalidStatusTransition
	}

	switch s.Status {
	case StatusPending, StatusReady, StatusFailedRetryable:
	default:
		return ErrInvalidStatusTransition
	}

	if now.IsZero() {
		return ErrInvalidUpdatedAt
	}

	s.Status = StatusCanceled
	s.ErrorType = nil
	s.ErrorCode = nil
	s.ErrorMsg = nil
	s.UpdatedAt = now.UTC()

	return s.Validate()
}

// MarkReversed records a full Stripe Transfer reversal.
//
// Card payment Refund and Stripe Transfer Reversal are separate operations and
// must be coordinated by the application layer.
func (s *BrandFeeSettlement) MarkReversed(
	stripeTransferReversalID string,
	now time.Time,
) error {
	if s == nil || s.Status != StatusTransferred {
		return ErrInvalidStatusTransition
	}
	if !isStripeTransferReversalID(stripeTransferReversalID) {
		return ErrInvalidStripeTransferReversalID
	}
	if now.IsZero() {
		return ErrInvalidReversedAt
	}

	reversedAt := now.UTC()

	s.StripeTransferReversalID = stripeTransferReversalID
	s.Status = StatusReversed
	s.ErrorType = nil
	s.ErrorCode = nil
	s.ErrorMsg = nil
	s.ReversedAt = &reversedAt
	s.UpdatedAt = reversedAt

	return s.Validate()
}

// Validate verifies all BrandFeeSettlement persistence invariants.
func (s BrandFeeSettlement) Validate() error {
	if s.ID == "" || strings.Contains(s.ID, "/") {
		return ErrInvalidID
	}
	if s.OrderID == "" {
		return ErrInvalidOrderID
	}
	if s.PaymentID == "" {
		return ErrInvalidPaymentID
	}

	// Current AMOL payment documents use the Order ID as PaymentID.
	if s.PaymentID != s.OrderID {
		return ErrPaymentOrderMismatch
	}
	if s.OrderItemIndex < 0 {
		return ErrInvalidOrderItemIndex
	}
	if s.ResaleID == "" {
		return ErrInvalidResaleID
	}

	expectedID, err := NewID(s.PaymentID, s.OrderItemIndex)
	if err != nil {
		return err
	}
	if s.ID != expectedID {
		return ErrInvalidID
	}

	if err := s.BrandIdentity().Validate(); err != nil {
		return err
	}
	if !isStripePaymentIntentID(s.StripePaymentIntentID) {
		return ErrInvalidStripePaymentIntentID
	}
	if !isStripeChargeID(s.StripeChargeID) {
		return ErrInvalidStripeChargeID
	}
	if s.TransferGroup == "" {
		return ErrInvalidTransferGroup
	}
	if s.BrandFeeAmount <= 0 {
		return ErrInvalidBrandFeeAmount
	}
	if s.Currency != CurrencyJPY {
		return ErrInvalidCurrency
	}
	if !IsValidStatus(s.Status) {
		return ErrInvalidStatus
	}
	if s.CreatedAt.IsZero() {
		return ErrInvalidCreatedAt
	}
	if s.UpdatedAt.IsZero() || s.UpdatedAt.Before(s.CreatedAt) {
		return ErrInvalidUpdatedAt
	}

	if err := validateOptionalErrorString(s.ErrorType, ErrInvalidErrorType); err != nil {
		return err
	}
	if err := validateOptionalErrorString(s.ErrorCode, ErrInvalidErrorCode); err != nil {
		return err
	}
	if err := validateOptionalErrorString(s.ErrorMsg, ErrInvalidErrorMsg); err != nil {
		return err
	}

	switch s.Status {
	case StatusPending, StatusReady, StatusTransferring, StatusCanceled:
		if s.StripeTransferID != "" ||
			s.StripeTransferReversalID != "" ||
			s.TransferredAt != nil ||
			s.ReversedAt != nil {
			return ErrInvalidStatus
		}
		if s.ErrorType != nil || s.ErrorCode != nil || s.ErrorMsg != nil {
			return ErrInvalidStatus
		}

	case StatusFailedRetryable, StatusFailed:
		if s.StripeTransferID != "" ||
			s.StripeTransferReversalID != "" ||
			s.TransferredAt != nil ||
			s.ReversedAt != nil {
			return ErrInvalidStatus
		}
		if err := validateFailureReason(s.ErrorType, s.ErrorCode, s.ErrorMsg); err != nil {
			return err
		}

	case StatusTransferred:
		if !isStripeTransferID(s.StripeTransferID) {
			return ErrInvalidStripeTransferID
		}
		if s.StripeTransferReversalID != "" {
			return ErrInvalidStripeTransferReversalID
		}
		if s.TransferredAt == nil || s.TransferredAt.IsZero() {
			return ErrInvalidTransferredAt
		}
		if s.TransferredAt.Before(s.CreatedAt) {
			return ErrInvalidTransferredAt
		}
		if s.ReversedAt != nil {
			return ErrInvalidReversedAt
		}
		if s.ErrorType != nil || s.ErrorCode != nil || s.ErrorMsg != nil {
			return ErrInvalidStatus
		}

	case StatusReversed:
		if !isStripeTransferID(s.StripeTransferID) {
			return ErrInvalidStripeTransferID
		}
		if !isStripeTransferReversalID(s.StripeTransferReversalID) {
			return ErrInvalidStripeTransferReversalID
		}
		if s.TransferredAt == nil || s.TransferredAt.IsZero() {
			return ErrInvalidTransferredAt
		}
		if s.TransferredAt.Before(s.CreatedAt) {
			return ErrInvalidTransferredAt
		}
		if s.ReversedAt == nil || s.ReversedAt.IsZero() {
			return ErrInvalidReversedAt
		}
		if s.ReversedAt.Before(*s.TransferredAt) {
			return ErrInvalidReversedAt
		}
		if s.ErrorType != nil || s.ErrorCode != nil || s.ErrorMsg != nil {
			return ErrInvalidStatus
		}
	}

	return nil
}

func validateFailureReason(
	errorType *string,
	errorCode *string,
	errorMsg *string,
) error {
	if err := validateOptionalErrorString(errorType, ErrInvalidErrorType); err != nil {
		return err
	}
	if err := validateOptionalErrorString(errorCode, ErrInvalidErrorCode); err != nil {
		return err
	}
	if err := validateOptionalErrorString(errorMsg, ErrInvalidErrorMsg); err != nil {
		return err
	}
	if errorType == nil && errorCode == nil && errorMsg == nil {
		return ErrFailureReasonRequired
	}

	return nil
}

func validateOptionalErrorString(value *string, invalidError error) error {
	if value != nil && *value == "" {
		return invalidError
	}

	return nil
}

func isStripeAccountID(value string) bool {
	return strings.HasPrefix(value, "acct_") && len(value) > len("acct_")
}

func isStripePaymentIntentID(value string) bool {
	return strings.HasPrefix(value, "pi_") && len(value) > len("pi_")
}

func isStripeChargeID(value string) bool {
	return strings.HasPrefix(value, "ch_") && len(value) > len("ch_")
}

func isStripeTransferID(value string) bool {
	return strings.HasPrefix(value, "tr_") && len(value) > len("tr_")
}

func isStripeTransferReversalID(value string) bool {
	return strings.HasPrefix(value, "trr_") && len(value) > len("trr_")
}
