// backend/internal/domain/brandFeeSettlement/repository_port.go
package brandFeeSettlement

import (
	"context"
	"errors"
	"time"
)

// CreateBrandFeeSettlementInput represents the persistence input used when a
// productBlueprint Brand fee is created for one successfully paid resale Order item.
//
// BrandFeeSettlementID must be generated deterministically with NewID from:
//
//	paymentID + "_resale_brand_fee_item_" + orderItemIndex
//
// Brand contains the immutable payout destination captured in the resale Order
// item BrandRevenueSnapshot.
//
// A newly created BrandFeeSettlement must be pending.
//
// Payment success creates only the financial record. ready represents the
// fulfillment boundary and must be reached later through a validated
// pending -> ready transition.
//
// Status may be empty so the repository implementation can normalize it to
// pending. Any non-empty status other than pending must be rejected.
type CreateBrandFeeSettlementInput struct {
	BrandFeeSettlementID string

	OrderID        string
	PaymentID      string
	OrderItemIndex int
	ResaleID       string

	Brand BrandIdentity

	StripePaymentIntentID string
	StripeChargeID        string

	TransferGroup string

	BrandFeeAmount int

	Currency string
	Status   Status
}

// UpdateBrandFeeSettlementInput represents one BrandFeeSettlement state
// transition.
//
// nil means the corresponding field is not supplied by the caller.
//
// StripeTransferID is set when the Brand Stripe Connect Transfer succeeds.
// StripeTransferReversalID is set when a completed Brand Transfer is reversed.
//
// Brand identity, Order item identity, payment identity, BrandFeeAmount,
// Currency, and CreatedAt are immutable and cannot be changed through this input.
//
// pending -> ready is the explicit fulfillment boundary.
// failed_retryable does not transition back to ready; it may be claimed directly
// for another Stripe Transfer attempt.
type UpdateBrandFeeSettlementInput struct {
	StripeTransferID *string

	StripeTransferReversalID *string

	Status *Status

	ErrorType *string
	ErrorCode *string
	ErrorMsg  *string
}

// ListTransferCandidatesInput defines the recovery boundary for Brand fee Stripe
// Transfer processing.
//
// Implementations must return only:
//   - ready
//   - failed_retryable
//   - transferring with UpdatedAt <= StaleBefore
//
// pending must never be returned because the resale fulfillment boundary has not
// yet made the Brand fee executable.
//
// A non-stale transferring record must not be returned because another worker may
// still own the transfer lease.
//
// Limit is the maximum total number of records returned by one scan.
type ListTransferCandidatesInput struct {
	StaleBefore time.Time
	Limit       int
}

// Repository defines persistence operations for productBlueprint Brand fees
// generated by consumer resale transactions.
//
// Persistence policy:
//   - Firestore collection: brandFeeSettlements
//   - one active resale Order item creates one BrandFeeSettlement
//   - document ID is deterministic BrandFeeSettlement.ID
//   - ID is generated by NewID(PaymentID, OrderItemIndex)
//   - one Payment may contain multiple BrandFeeSettlements
//   - multiple resale items belonging to the same Brand or Account remain
//     independent records
//   - one Payment must contain at most one BrandFeeSettlement per OrderItemIndex
//
// BrandFeeSettlement is intentionally separate from:
//   - settlement.Repository for primary List-sale sellers
//   - salesReceivable.Repository for consumer resale seller proceeds
//   - payment.RepositoryPort for buyer -> AMOL payments
//
// BrandFeeSettlement represents only:
//
//	AMOL Stripe Platform -> productBlueprint Brand Stripe Connected Account
//
// Repository implementations must persist and validate the complete immutable
// Brand identity captured at Order creation. Current Brand or Account state must
// never be re-resolved to change an existing record's payout destination.
type Repository interface {
	// GetByID returns one BrandFeeSettlement by deterministic document ID.
	//
	// ErrNotFound must be returned when the document does not exist.
	GetByID(
		ctx context.Context,
		brandFeeSettlementID string,
	) (BrandFeeSettlement, error)

	// ListByPaymentID returns every item-level BrandFeeSettlement belonging to one
	// Payment.
	//
	// Each returned record must represent a distinct OrderItemIndex.
	ListByPaymentID(
		ctx context.Context,
		paymentID string,
	) ([]BrandFeeSettlement, error)

	// ListByOrderID returns every item-level BrandFeeSettlement belonging to one
	// Order.
	//
	// PaymentID currently equals OrderID, but the Order boundary remains explicit
	// for application and refund use.
	ListByOrderID(
		ctx context.Context,
		orderID string,
	) ([]BrandFeeSettlement, error)

	// ListByBrandID returns Brand fee records attributable to one productBlueprint
	// Brand.
	//
	// Multiple Order items and multiple Payments may belong to the same Brand.
	ListByBrandID(
		ctx context.Context,
		brandID string,
	) ([]BrandFeeSettlement, error)

	// ListByCompanyID returns Brand fee records attributable to one Company.
	//
	// This supports Console financial and transaction queries while preserving
	// the immutable Brand payout identity captured at Order creation.
	ListByCompanyID(
		ctx context.Context,
		companyID string,
	) ([]BrandFeeSettlement, error)

	// ListByAccountID returns Brand fee records attributable to one Stripe
	// Connected Account payout identity.
	//
	// Multiple Brands may reference the same AccountID, but records remain
	// independent per resale Order item.
	ListByAccountID(
		ctx context.Context,
		accountID string,
	) ([]BrandFeeSettlement, error)

	// ListTransferCandidates returns BrandFeeSettlements that may require a
	// Stripe Transfer task to be present or retried.
	//
	// Implementations must include:
	//   - ready
	//   - failed_retryable
	//   - transferring with UpdatedAt <= StaleBefore
	//
	// Implementations must exclude:
	//   - pending
	//   - non-stale transferring
	//   - transferred
	//   - failed
	//   - canceled
	//   - reversed
	//
	// Results must contain no duplicate ID. Implementations should order older
	// UpdatedAt values first and use ID as the deterministic tie breaker before
	// applying Limit.
	ListTransferCandidates(
		ctx context.Context,
		in ListTransferCandidatesInput,
	) ([]BrandFeeSettlement, error)

	// Create creates one new pending BrandFeeSettlement.
	//
	// Implementations must reject an existing BrandFeeSettlementID rather than
	// overwrite it and return ErrConflict. The deterministic ID therefore makes
	// duplicate payment-success handling idempotent.
	//
	// Brand must contain:
	//   - BrandID
	//   - CompanyID
	//   - AccountID
	//   - StripeAccountID
	//
	// The incoming allocation must also contain:
	//   - OrderID
	//   - PaymentID
	//   - OrderItemIndex
	//   - ResaleID
	//   - StripePaymentIntentID
	//   - StripeChargeID
	//   - TransferGroup
	//   - BrandFeeAmount
	//   - Currency
	//
	// BrandFeeSettlementID must equal NewID(PaymentID, OrderItemIndex).
	//
	// An empty Status may be normalized to pending. Any non-empty Status other
	// than pending must be rejected.
	//
	// ready must never be accepted at creation because it means that the required
	// resale fulfillment boundary has already been crossed.
	Create(
		ctx context.Context,
		in CreateBrandFeeSettlementInput,
	) (BrandFeeSettlement, error)

	// UpdateByID executes one validated BrandFeeSettlement state transition.
	//
	// Implementations must read the current record and execute domain transition
	// methods before persisting the resulting complete entity.
	//
	// The following fields are immutable:
	//   - ID
	//   - OrderID
	//   - PaymentID
	//   - OrderItemIndex
	//   - ResaleID
	//   - BrandID
	//   - CompanyID
	//   - AccountID
	//   - StripeAccountID
	//   - StripePaymentIntentID
	//   - StripeChargeID
	//   - TransferGroup
	//   - BrandFeeAmount
	//   - Currency
	//   - CreatedAt
	//
	// Valid lifecycle transitions include:
	//   - pending -> ready
	//   - ready -> transferring
	//   - failed_retryable -> transferring
	//   - stale transferring -> transferring through ReclaimTransfer
	//   - transferring -> transferred
	//   - transferring -> failed_retryable
	//   - transferring -> failed
	//   - pending/ready/failed_retryable -> canceled
	//   - transferred -> reversed
	//
	// Implementations must validate the complete resulting entity before
	// persistence.
	UpdateByID(
		ctx context.Context,
		brandFeeSettlementID string,
		patch UpdateBrandFeeSettlementInput,
	) (BrandFeeSettlement, error)
}

// Repository errors.
var (
	ErrNotFound = errors.New("brandFeeSettlement: not found")
	ErrConflict = errors.New("brandFeeSettlement: conflict")
)
