// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTetB8PcVlSHhXbItMZv2thd5lY4d5nIQ',
    appId: '1:871263659099:web:0d4bbdc36e59d7ed8d4b7e',
    messagingSenderId: '871263659099',
    projectId: 'narratives-development-26c2d',
    authDomain: 'narratives-development-26c2d.firebaseapp.com',
    storageBucket: 'narratives-development-26c2d.firebasestorage.app',
    measurementId: 'G-T77JW1DF4V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYGIzM85qj1k-hQ2sdFGyaLNr2zENJ42w',
    appId: '1:871263659099:android:3d3c35649010d54b8d4b7e',
    messagingSenderId: '871263659099',
    projectId: 'narratives-development-26c2d',
    storageBucket: 'narratives-development-26c2d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbhBM2zKBEdK4kqbveBc05VMOKZEdB5WU',
    appId: '1:871263659099:ios:c65e6fd8fcb0bf758d4b7e',
    messagingSenderId: '871263659099',
    projectId: 'narratives-development-26c2d',
    storageBucket: 'narratives-development-26c2d.firebasestorage.app',
    iosClientId: '871263659099-s3mpeo9rqe9te4s7so2mmd1bi8abrfva.apps.googleusercontent.com',
    iosBundleId: 'com.example.inspector',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbhBM2zKBEdK4kqbveBc05VMOKZEdB5WU',
    appId: '1:871263659099:ios:c65e6fd8fcb0bf758d4b7e',
    messagingSenderId: '871263659099',
    projectId: 'narratives-development-26c2d',
    storageBucket: 'narratives-development-26c2d.firebasestorage.app',
    iosClientId: '871263659099-s3mpeo9rqe9te4s7so2mmd1bi8abrfva.apps.googleusercontent.com',
    iosBundleId: 'com.example.inspector',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTetB8PcVlSHhXbItMZv2thd5lY4d5nIQ',
    appId: '1:871263659099:web:ae0d904bb4ff15aa8d4b7e',
    messagingSenderId: '871263659099',
    projectId: 'narratives-development-26c2d',
    authDomain: 'narratives-development-26c2d.firebaseapp.com',
    storageBucket: 'narratives-development-26c2d.firebasestorage.app',
    measurementId: 'G-R2N2CLRK87',
  );
}
