// frontend\transaction\src\infrastructure\mockdata\mockdata.tsx
import type {
  Transaction,
  TransactionType,
} from "../../../../shell/src/shared/types/transaction";

/**
 * TRANSACTIONS
 * backend/internal/domain/transaction/entity.go と
 * frontend/shell/src/shared/types/transaction.ts に準拠したモックデータ。
 *
 * - timestamp は ISO8601 形式 (例: "2024-03-15T23:32:00Z")
 * - 通貨は JPY 固定
 * - type は "受取" → "receive", "送金" → "send" に変換
 * - amount は常に正数（方向は type で表す）
 */
export const TRANSACTIONS: Transaction[] = [
  {
    id: "tx_001",
    accountId: "account_001",
    brandName: "LUMINA Fashion",
    type: "receive" as TransactionType,
    amount: 125000,
    currency: "JPY",
    fromAccount: "株式会社○○商事",
    toAccount: "LUMINA Fashion",
    timestamp: "2024-03-15T23:32:00Z",
    description: "商品購入代金",
  },
  {
    id: "tx_002",
    accountId: "account_002",
    brandName: "NEXUS Street",
    type: "send" as TransactionType,
    amount: 89000,
    currency: "JPY",
    fromAccount: "NEXUS Street",
    toAccount: "△△サプライヤー",
    timestamp: "2024-03-15T22:15:00Z",
    description: "サプライヤー支払い",
  },
  {
    id: "tx_003",
    accountId: "account_001",
    brandName: "LUMINA Fashion",
    type: "receive" as TransactionType,
    amount: 230000,
    currency: "JPY",
    fromAccount: "VIP会員様",
    toAccount: "LUMINA Fashion",
    timestamp: "2024-03-15T20:45:00Z",
    description: "VIP会員購入",
  },
  {
    id: "tx_004",
    accountId: "account_002",
    brandName: "NEXUS Street",
    type: "receive" as TransactionType,
    amount: 54000,
    currency: "JPY",
    fromAccount: "NFT購入者",
    toAccount: "NEXUS Street",
    timestamp: "2024-03-15T19:20:00Z",
    description: "トークン販売",
  },
  {
    id: "tx_005",
    accountId: "account_002",
    brandName: "NEXUS Street",
    type: "receive" as TransactionType,
    amount: 156000,
    currency: "JPY",
    fromAccount: "コラボ先企業",
    toAccount: "NEXUS Street",
    timestamp: "2024-03-15T18:10:00Z",
    description: "コラボ商品売上",
  },
  {
    id: "tx_006",
    accountId: "account_001",
    brandName: "LUMINA Fashion",
    type: "send" as TransactionType,
    amount: 175000,
    currency: "JPY",
    fromAccount: "LUMINA Fashion",
    toAccount: "製造パートナー",
    timestamp: "2024-03-15T01:20:00Z",
    description: "製造委託費用",
  },
  {
    id: "tx_007",
    accountId: "account_001",
    brandName: "LUMINA Fashion",
    type: "receive" as TransactionType,
    amount: 98000,
    currency: "JPY",
    fromAccount: "オンラインストア",
    toAccount: "LUMINA Fashion",
    timestamp: "2024-03-15T00:10:00Z",
    description: "EC売上",
  },
  {
    id: "tx_008",
    accountId: "account_002",
    brandName: "NEXUS Street",
    type: "send" as TransactionType,
    amount: 65000,
    currency: "JPY",
    fromAccount: "NEXUS Street",
    toAccount: "広告代理店",
    timestamp: "2024-03-14T23:30:00Z",
    description: "広告宣伝費",
  },
  {
    id: "tx_009",
    accountId: "account_001",
    brandName: "LUMINA Fashion",
    type: "receive" as TransactionType,
    amount: 315000,
    currency: "JPY",
    fromAccount: "百貨店",
    toAccount: "LUMINA Fashion",
    timestamp: "2024-03-14T20:25:00Z",
    description: "店頭売上",
  },
  {
    id: "tx_010",
    accountId: "account_002",
    brandName: "NEXUS Street",
    type: "send" as TransactionType,
    amount: 42000,
    currency: "JPY",
    fromAccount: "NEXUS Street",
    toAccount: "素材サプライヤー",
    timestamp: "2024-03-14T19:15:00Z",
    description: "材料仕入れ",
  },
  {
    id: "tx_011",
    accountId: "account_001",
    brandName: "LUMINA Fashion",
    type: "receive" as TransactionType,
    amount: 76000,
    currency: "JPY",
    fromAccount: "直営店",
    toAccount: "LUMINA Fashion",
    timestamp: "2024-03-14T18:00:00Z",
    description: "キャンペーン売上",
  },
  {
    id: "tx_012",
    accountId: "account_002",
    brandName: "NEXUS Street",
    type: "send" as TransactionType,
    amount: 12000,
    currency: "JPY",
    fromAccount: "NEXUS Street",
    toAccount: "配送会社",
    timestamp: "2024-03-14T17:40:00Z",
    description: "配送費用",
  },
];
