// backend/internal/adapters/in/http/mall/handler/transfer_handler.go
package mallHandler

import (
	"context"
	"errors"
	"net/http"

	"narratives/internal/adapters/in/http/middleware"
	"narratives/internal/application/usecase"
)

// ScanTransferUsecase is the dependency for:
// POST /mall/me/orders/scan/transfer
type ScanTransferUsecase interface {
	TransferToAvatarByVerifiedScan(
		ctx context.Context,
		in usecase.TransferByVerifiedScanInput,
	) (usecase.TransferByVerifiedScanResult, error)
}

// ScanTransferResult is the response "data" shape expected by frontend.
type ScanTransferResult struct {
	AvatarID  string `json:"avatarId"`
	ProductID string `json:"productId"`

	Matched bool `json:"matched"`

	MatchedOrderID   string `json:"matchedOrderId,omitempty"`
	MatchedItemIndex *int   `json:"matchedItemIndex,omitempty"`

	// Transfer result
	TxSignature string `json:"txSignature,omitempty"`

	// Display names resolved by backend.
	// Frontend modal should use these instead of wallet address fallback.
	FromDisplayName string `json:"fromDisplayName,omitempty"`
	ToDisplayName   string `json:"toDisplayName,omitempty"`

	// tokens/{productId}.toAddress updated?
	UpdatedToAddress bool `json:"updatedToAddress,omitempty"`

	// transferred Bubblegum V2 cNFT assetId
	AssetID string `json:"assetId,omitempty"`
}

// TransferHandler handles:
// POST /mall/me/orders/scan/transfer
type TransferHandler struct {
	uc ScanTransferUsecase
}

// NewTransferHandler creates handler.
// NOTE: This handler assumes AvatarContextMiddleware is enabled for this route.
func NewTransferHandler(
	uc ScanTransferUsecase,
) http.Handler {
	return &TransferHandler{
		uc: uc,
	}
}

func (h *TransferHandler) ServeHTTP(
	w http.ResponseWriter,
	r *http.Request,
) {
	w.Header().Set(
		"Content-Type",
		"application/json",
	)

	// Preflight
	if r.Method == http.MethodOptions {
		w.Header().Set(
			"Access-Control-Allow-Headers",
			"Authorization,Content-Type,Idempotency-Key",
		)

		w.WriteHeader(http.StatusNoContent)
		return
	}

	if r.Method != http.MethodPost {
		methodNotAllowed(w)
		return
	}

	if h == nil || h.uc == nil {
		internalError(
			w,
			"transfer usecase not configured",
		)
		return
	}

	// /mall/me/... is auth-required (normally enforced by middleware)
	auth := r.Header.Get("Authorization")
	if auth == "" {
		writeJSON(
			w,
			http.StatusUnauthorized,
			map[string]any{
				"error": "authorization header is required",
			},
		)
		return
	}

	_, ok := middleware.CurrentUserUID(r)
	if !ok {
		writeJSON(
			w,
			http.StatusUnauthorized,
			map[string]any{
				"error": "unauthorized: missing uid",
			},
		)
		return
	}

	// Idempotency-Key must be generated by the caller and reused when the same
	// logical transfer request is retried.
	//
	// Do not generate this value on the server because a retried HTTP request
	// must reach the usecase with the exact same operationId.
	operationID := r.Header.Get("Idempotency-Key")
	if operationID == "" {
		badRequest(
			w,
			"Idempotency-Key header is required",
		)
		return
	}

	// Body: productId only (avatarId is taken from context)
	var body struct {
		ProductID string `json:"productId"`
	}

	if err := readJSON(
		r,
		&body,
	); err != nil {
		writeJSON(
			w,
			http.StatusBadRequest,
			map[string]any{
				"error":   "invalid json",
				"message": err.Error(),
			},
		)
		return
	}

	productID := body.ProductID
	if productID == "" {
		badRequest(
			w,
			"productId is required",
		)
		return
	}

	// avatarId is resolved and stored by AvatarContextMiddleware (required)
	avatarID, ok :=
		middleware.CurrentAvatarID(r)
	if !ok || avatarID == "" {
		// This should not happen if requireAvatarContext is wired.
		// Treat as service misconfiguration to make the bug obvious.
		writeJSON(
			w,
			http.StatusServiceUnavailable,
			map[string]any{
				"error":   "avatar_context_missing",
				"message": "AvatarContextMiddleware did not provide avatarId",
			},
		)
		return
	}

	ucOut, err :=
		h.uc.TransferToAvatarByVerifiedScan(
			r.Context(),
			usecase.TransferByVerifiedScanInput{
				AvatarID:    avatarID,
				ProductID:   productID,
				OperationID: operationID,
			},
		)
	if err != nil {
		if errors.Is(
			err,
			usecase.ErrTransferNotMatched,
		) {
			out := &ScanTransferResult{
				AvatarID:  avatarID,
				ProductID: productID,
				Matched:   false,
			}

			writeJSON(
				w,
				http.StatusOK,
				map[string]any{
					"data": out,
				},
			)
			return
		}

		if errors.Is(
			err,
			usecase.ErrTransferBlockedByReturn,
		) {
			writeJSON(
				w,
				http.StatusConflict,
				map[string]any{
					"error":     "return_in_progress_opened",
					"message":   "返品申請中の商品で開封が確認されました。返品区分を「開封後の返品」に変更しました。Token Transfer は実行していません。",
					"avatarId":  avatarID,
					"productId": productID,
					"orderId":   ucOut.MatchedOrderID,
					"itemIndex": ucOut.MatchedItemIndex,
				},
			)
			return
		}
		if errors.Is(
			err,
			context.Canceled,
		) ||
			errors.Is(
				err,
				context.DeadlineExceeded,
			) {
			writeJSON(
				w,
				http.StatusRequestTimeout,
				map[string]any{
					"error":     "request canceled",
					"message":   err.Error(),
					"avatarId":  avatarID,
					"productId": productID,
				},
			)
			return
		}

		writeJSON(
			w,
			http.StatusInternalServerError,
			map[string]any{
				"error":     "transfer failed",
				"message":   err.Error(),
				"avatarId":  avatarID,
				"productId": productID,
			},
		)
		return
	}

	matchedItemIndex := ucOut.MatchedItemIndex

	out := &ScanTransferResult{
		AvatarID:         avatarID,
		ProductID:        productID,
		Matched:          true,
		MatchedOrderID:   ucOut.MatchedOrderID,
		MatchedItemIndex: &matchedItemIndex,
		TxSignature:      ucOut.TxSignature,
		FromDisplayName:  ucOut.FromDisplayName,
		ToDisplayName:    ucOut.ToDisplayName,
		UpdatedToAddress: true,
		AssetID:          ucOut.AssetID,
	}

	writeJSON(
		w,
		http.StatusOK,
		map[string]any{
			"data": out,
		},
	)
}
