// backend/internal/domain/salesReceivable/repository_port.go
package salesReceivable

import (
	"context"
	"errors"
)

// Repository errors.
var (
	ErrNotFound = errors.New("salesReceivable: not found")
	ErrConflict = errors.New("salesReceivable: conflict")
)

// ListAvailableByUserIDInput defines the selection boundary used when preparing
// a future bank payout.
//
// Only StatusAvailable receivables belonging to UserID may be returned.
//
// Limit must be positive. Implementations should return older AvailableAt values
// first and use ID as the deterministic tie breaker.
type ListAvailableByUserIDInput struct {
	UserID string
	Limit  int
}

// Repository defines persistence operations for resale sales receivables.
//
// Persistence policy:
//   - Firestore collection: salesReceivables
//   - one resale Order item creates one SalesReceivable
//   - document ID: deterministic SalesReceivable.ID
//   - ID is generated by NewID(PaymentID, OrderItemIndex)
//   - one Payment may contain multiple SalesReceivables
//   - multiple items belonging to the same seller remain independent receivables
//   - one Payment must contain at most one receivable for each OrderItemIndex
//
// Repository implementations must validate the complete SalesReceivable entity
// before persistence.
//
// Repository implementations must never store bank-account details in a
// SalesReceivable. Bank destination data belongs to PayoutAccount and is
// snapshotted separately when a BankPayout is created.
type Repository interface {
	// GetByID returns one SalesReceivable by its deterministic document ID.
	//
	// ErrNotFound must be returned when the document does not exist.
	GetByID(
		ctx context.Context,
		receivableID string,
	) (SalesReceivable, error)

	// ListByPaymentID returns every item-level SalesReceivable belonging to one
	// Payment.
	//
	// Each returned receivable must represent a distinct OrderItemIndex.
	ListByPaymentID(
		ctx context.Context,
		paymentID string,
	) ([]SalesReceivable, error)

	// ListByOrderID returns every item-level SalesReceivable belonging to one
	// Order.
	//
	// PaymentID currently equals OrderID, but the Order boundary remains explicit
	// for application and query use.
	ListByOrderID(
		ctx context.Context,
		orderID string,
	) ([]SalesReceivable, error)

	// ListByAvatarID returns receivables attributable to one resale seller Avatar.
	//
	// Multiple receivables may belong to the same Avatar within one Payment.
	ListByAvatarID(
		ctx context.Context,
		avatarID string,
	) ([]SalesReceivable, error)

	// ListByUserID returns receivables attributable to one authenticated user.
	//
	// A user may have multiple item-level receivables in multiple lifecycle
	// states.
	ListByUserID(
		ctx context.Context,
		userID string,
	) ([]SalesReceivable, error)

	// ListByPayoutAccountID returns receivables associated with one registered
	// payout-account identity.
	//
	// PayoutAccountID currently equals UserID and is captured from the Order
	// SellerSnapshot. Multiple independent item-level receivables may reference
	// the same PayoutAccountID.
	ListByPayoutAccountID(
		ctx context.Context,
		payoutAccountID string,
	) ([]SalesReceivable, error)

	// ListByBankPayoutID returns every receivable assigned to one BankPayout.
	//
	// Normally the returned receivables are reserved or paid. Historical paid
	// receivables must remain queryable after payout completion.
	ListByBankPayoutID(
		ctx context.Context,
		bankPayoutID string,
	) ([]SalesReceivable, error)

	// ListAvailableByUserID returns item-level receivables eligible to be
	// included in a future BankPayout.
	//
	// Implementations must return only:
	//
	//   - UserID == in.UserID
	//   - Status == StatusAvailable
	//   - BankPayoutID == ""
	//
	// Implementations should order older AvailableAt values first and use ID as
	// the tie breaker before applying Limit.
	//
	// This method only selects candidates. It does not reserve them. Reservation
	// must occur through a transaction boundary when BankPayout creation is
	// implemented.
	ListAvailableByUserID(
		ctx context.Context,
		in ListAvailableByUserIDInput,
	) ([]SalesReceivable, error)

	// Create persists a new pending item-level SalesReceivable.
	//
	// Implementations must reject an existing ID rather than overwrite it and
	// return ErrConflict. Deterministic IDs therefore provide idempotency for
	// payment-success processing.
	//
	// The incoming entity must:
	//
	//   - pass Validate()
	//   - have ID == NewID(PaymentID, OrderItemIndex)
	//   - have StatusPending
	//   - have no BankPayoutID
	//   - have no lifecycle timestamp other than CreatedAt / UpdatedAt
	//
	// Implementations must not silently normalize or modify item identity, seller
	// identity, amounts, timestamps, or status.
	Create(
		ctx context.Context,
		receivable SalesReceivable,
	) (SalesReceivable, error)

	// Update replaces the persisted SalesReceivable state for the same ID.
	//
	// Implementations must return ErrNotFound when the document does not exist.
	//
	// The following fields are immutable:
	//
	//   - ID
	//   - OrderID
	//   - PaymentID
	//   - OrderItemIndex
	//   - ResaleID
	//   - AvatarID
	//   - UserID
	//   - PayoutAccountID
	//   - GrossAmount
	//   - PlatformFeeAmount
	//   - ReceivableAmount
	//   - Currency
	//   - CreatedAt
	//
	// Status and lifecycle fields may change only through valid domain methods
	// such as MarkAvailable, Reserve, ReleaseReservation, MarkPaid, and Cancel.
	//
	// Implementations must validate the complete resulting entity before
	// persistence.
	Update(
		ctx context.Context,
		receivable SalesReceivable,
	) (SalesReceivable, error)
}
