// backend\internal\domain\tokenOperation\entity.go
package tokenOperation

import (
	"errors"
	"strings"
)

// ===============================
// Types (mirror TS)
// ===============================

// TokenOperation mirrors web-app/src/shared/types/tokenOperation.ts
type TokenOperation struct {
	ID               string
	TokenBlueprintID string
	AssigneeID       string
}

// TokenOperationExtended mirrors TokenOperationExtended (server-side join result)
type TokenOperationExtended struct {
	TokenOperation
	TokenName    string
	Symbol       string
	BrandID      string
	AssigneeName string
	BrandName    string
}

// ===============================
// Errors
// ===============================

var (
	ErrInvalidID               = errors.New("tokenOperation: invalid id")
	ErrInvalidTokenBlueprintID = errors.New("tokenOperation: invalid tokenBlueprintId")
	ErrInvalidAssigneeID       = errors.New("tokenOperation: invalid assigneeId")

	// Extended-only fields
	ErrInvalidTokenName    = errors.New("tokenOperation: invalid tokenName")
	ErrInvalidSymbol       = errors.New("tokenOperation: invalid symbol")
	ErrInvalidBrandID      = errors.New("tokenOperation: invalid brandId")
	ErrInvalidAssigneeName = errors.New("tokenOperation: invalid assigneeName")
	ErrInvalidBrandName    = errors.New("tokenOperation: invalid brandName")
)

// ===============================
// Policy (align with tokenOperationConstants.ts)
// Set limits to 0 to disable those checks.
// ===============================

var (
	EnforceIDPrefix        = false
	TokenOperationIDPrefix = ""
	MaxIDLength            = 128

	MaxNameLength   = 200
	MaxSymbolLength = 32
)

// ===============================
// Constructors
// ===============================

func New(id, tokenBlueprintID, assigneeID string) (TokenOperation, error) {
	op := TokenOperation{
		ID:               strings.TrimSpace(id),
		TokenBlueprintID: strings.TrimSpace(tokenBlueprintID),
		AssigneeID:       strings.TrimSpace(assigneeID),
	}
	if err := op.validate(); err != nil {
		return TokenOperation{}, err
	}
	return op, nil
}

// Helper for create-usecase where ID is generated by server.
func NewWithGeneratedID(id string, tokenBlueprintID, assigneeID string) (TokenOperation, error) {
	return New(id, tokenBlueprintID, assigneeID)
}

// Build extended model (all extra fields are required here)
func NewExtended(
	base TokenOperation,
	tokenName, symbol, brandID, assigneeName, brandName string,
) (TokenOperationExtended, error) {
	e := TokenOperationExtended{
		TokenOperation: base,
		TokenName:      strings.TrimSpace(tokenName),
		Symbol:         strings.TrimSpace(symbol),
		BrandID:        strings.TrimSpace(brandID),
		AssigneeName:   strings.TrimSpace(assigneeName),
		BrandName:      strings.TrimSpace(brandName),
	}
	if err := e.validateExtended(); err != nil {
		return TokenOperationExtended{}, err
	}
	return e, nil
}

// ===============================
// Behavior
// ===============================

func (t *TokenOperation) ReassignAssignee(assigneeID string) error {
	assigneeID = strings.TrimSpace(assigneeID)
	if assigneeID == "" {
		return ErrInvalidAssigneeID
	}
	t.AssigneeID = assigneeID
	return nil
}

func (t *TokenOperation) ReassignBlueprint(tokenBlueprintID string) error {
	tokenBlueprintID = strings.TrimSpace(tokenBlueprintID)
	if tokenBlueprintID == "" {
		return ErrInvalidTokenBlueprintID
	}
	t.TokenBlueprintID = tokenBlueprintID
	return nil
}

// ===============================
// Validation
// ===============================

func (t TokenOperation) validate() error {
	if t.ID == "" {
		return ErrInvalidID
	}
	if EnforceIDPrefix && TokenOperationIDPrefix != "" && !strings.HasPrefix(t.ID, TokenOperationIDPrefix) {
		return ErrInvalidID
	}
	if MaxIDLength > 0 && len(t.ID) > MaxIDLength {
		return ErrInvalidID
	}
	if t.TokenBlueprintID == "" {
		return ErrInvalidTokenBlueprintID
	}
	if t.AssigneeID == "" {
		return ErrInvalidAssigneeID
	}
	return nil
}

func (t TokenOperationExtended) validateExtended() error {
	// base must be valid
	if err := t.TokenOperation.validate(); err != nil {
		return err
	}
	if t.TokenName = strings.TrimSpace(t.TokenName); t.TokenName == "" {
		return ErrInvalidTokenName
	}
	if MaxNameLength > 0 && len([]rune(t.TokenName)) > MaxNameLength {
		return ErrInvalidTokenName
	}
	if t.Symbol = strings.TrimSpace(t.Symbol); t.Symbol == "" {
		return ErrInvalidSymbol
	}
	if MaxSymbolLength > 0 && len([]rune(t.Symbol)) > MaxSymbolLength {
		return ErrInvalidSymbol
	}
	if t.BrandID = strings.TrimSpace(t.BrandID); t.BrandID == "" {
		return ErrInvalidBrandID
	}
	if t.AssigneeName = strings.TrimSpace(t.AssigneeName); t.AssigneeName == "" {
		return ErrInvalidAssigneeName
	}
	if MaxNameLength > 0 && len([]rune(t.AssigneeName)) > MaxNameLength {
		return ErrInvalidAssigneeName
	}
	if t.BrandName = strings.TrimSpace(t.BrandName); t.BrandName == "" {
		return ErrInvalidBrandName
	}
	if MaxNameLength > 0 && len([]rune(t.BrandName)) > MaxNameLength {
		return ErrInvalidBrandName
	}
	return nil
}
