// backend/internal/domain/bankPayout/repository_port.go
package bankPayout

import (
	"context"
	"errors"
)

// Repository errors.
var (
	ErrNotFound = errors.New("bankPayout: not found")
	ErrConflict = errors.New("bankPayout: conflict")
)

// Repository defines persistence operations for resale seller bank payouts.
//
// Persistence policy:
//   - Firestore collection: bankPayouts
//   - one SalesReceivable creates at most one BankPayout
//   - document ID: deterministic BankPayout.ID
//   - ID is generated by NewID(SalesReceivableID)
//   - one BankPayout pays exactly one item-level SalesReceivable
//   - bank destination data is snapshotted when the BankPayout is created
//   - plaintext bank account numbers must never be persisted
//   - AccountNumberCiphertext must remain encrypted at rest and must never be
//     exposed through buyer/seller-facing HTTP responses
//
// Repository implementations must validate the complete BankPayout entity
// before persistence.
//
// Cross-aggregate coordination with SalesReceivable is intentionally not hidden
// inside this repository interface. The application/infrastructure layer must
// provide the transactional boundary that coordinates:
//
//   - SalesReceivable available -> reserved
//   - BankPayout creation
//
// and, after successful payout execution:
//
//   - BankPayout processing -> paid
//   - SalesReceivable reserved -> paid
//
// This repository is responsible only for BankPayout persistence and must never
// silently mutate SalesReceivable state.
type Repository interface {
	// CreateIfAbsent persists a new pending BankPayout when its deterministic ID
	// does not already exist.
	//
	// Idempotency:
	//   - BankPayout.ID must equal NewID(SalesReceivableID).
	//   - If that ID already exists and represents the same immutable payout
	//     scope, the existing entity must be returned with created=false.
	//   - An existing paid payout must never be reset to pending.
	//   - If the existing document has the same ID but different immutable
	//     payout identity or amount/destination data, ErrConflict must be returned.
	//
	// The incoming entity must:
	//   - pass Validate()
	//   - have StatusPending
	//   - have an empty ProviderPayoutID
	//   - have nil ProcessingAt / PaidAt
	//   - have no failure reason
	//
	// Implementations must not silently normalize or modify identity, amount,
	// bank destination, timestamps, or status.
	CreateIfAbsent(
		ctx context.Context,
		payout BankPayout,
	) (persisted BankPayout, created bool, err error)

	// GetByID returns one BankPayout by its deterministic document ID.
	//
	// ErrNotFound must be returned when the document does not exist.
	GetByID(
		ctx context.Context,
		payoutID string,
	) (BankPayout, error)

	// GetBySalesReceivableID returns the BankPayout belonging to one
	// SalesReceivable.
	//
	// Because BankPayout ID is deterministic from SalesReceivableID, repository
	// implementations may resolve this as:
	//
	//	NewID(salesReceivableID) -> GetByID(...)
	//
	// ErrNotFound must be returned when no BankPayout exists.
	GetBySalesReceivableID(
		ctx context.Context,
		salesReceivableID string,
	) (BankPayout, error)

	// Update replaces the persisted BankPayout state for the same ID.
	//
	// Implementations must return ErrNotFound when the document does not exist.
	//
	// The following fields are immutable after creation:
	//   - ID
	//   - SalesReceivableID
	//   - OrderID
	//   - PaymentID
	//   - OrderItemIndex
	//   - ResaleID
	//   - SellerUserID
	//   - PayoutAccountID
	//   - BankDestination
	//   - Amount
	//   - Currency
	//   - CreatedAt
	//
	// The following fields may change only through valid domain lifecycle
	// methods such as StartProcessing, ReclaimProcessing, MarkPaid,
	// MarkFailedRetryable, and MarkFailed:
	//   - Status
	//   - ProviderPayoutID
	//   - ErrorType
	//   - ErrorCode
	//   - ErrorMsg
	//   - UpdatedAt
	//   - ProcessingAt
	//   - PaidAt
	//
	// Implementations must validate both:
	//   - that immutable fields match the currently persisted entity
	//   - that the complete resulting entity passes Validate()
	//
	// An attempted immutable-field change must return ErrConflict.
	Update(
		ctx context.Context,
		payout BankPayout,
	) (BankPayout, error)
}
